const TP_MARKER = '681967';
const BOOKING_AID = '2709056';

export const BLOG_POSTS = [
  {
    slug: 'cheapest-flights-from-los-angeles-2026',
    date: '2026-03-06',
    image: '✈️',
    title_en: 'Cheapest Flights from Los Angeles in 2026',
    title_ru: 'Самые дешёвые рейсы из Лос-Анджелеса в 2026',
    desc_en: 'Top 10 budget destinations from LAX with prices starting at $24. Tips on finding the best deals.',
    desc_ru: 'Топ-10 бюджетных направлений из LAX с ценами от $24. Советы по поиску лучших предложений.',
    tags: ['flights', 'budget', 'LAX'],
    content_en: [
      { type: 'p', text: 'Los Angeles International Airport (LAX) is one of the busiest hubs in the US, which means incredible competition among airlines — and great prices for travelers. Here are the cheapest destinations you can fly to from LAX in 2026.' },
      { type: 'h2', text: '1. San Francisco (SFO) — from $24' },
      { type: 'p', text: 'The short hop to San Francisco is one of the cheapest domestic routes. Budget carriers like Frontier (F9) offer direct flights for as low as $24. Best booked 2-3 weeks in advance.' },
      { type: 'cta', text: 'Search LAX → SFO flights', link: `/en/flights/lax-sfo` },
      { type: 'h2', text: '2. New York (JFK) — from $102' },
      { type: 'p', text: 'Cross-country flights to NYC start at $102 with one stop. Direct flights on JetBlue and American Airlines average $125-180. Tuesday departures are cheapest.' },
      { type: 'cta', text: 'Search LAX → JFK flights', link: `/en/flights/lax-jfk` },
      { type: 'h2', text: '3. Las Vegas (LAS) — from $29' },
      { type: 'p', text: 'The classic weekend getaway. Spirit and Frontier dominate this route with sub-$30 fares. The 1-hour flight makes it perfect for spontaneous trips.' },
      { type: 'h2', text: '4. Seattle (SEA) — from $49' },
      { type: 'p', text: 'Alaska Airlines and budget carriers compete aggressively on this route. Best prices in shoulder season (April-May, September-October).' },
      { type: 'h2', text: '5. Cancún (CUN) — from $150' },
      { type: 'p', text: 'Mexico\'s beach paradise is surprisingly affordable from LA. Volaris and VivaAerobus offer the lowest fares. Off-season (May-November) brings prices down to $150 round-trip.' },
      { type: 'cta', text: 'Search LAX → CUN flights', link: `/en/flights/lax-cun` },
      { type: 'h2', text: '6. Tokyo (NRT) — from $450' },
      { type: 'p', text: 'Asia-bound travelers will find LAX has the most options for Japan. ANA and JAL offer competitive prices, especially in January-March (excluding holidays).' },
      { type: 'cta', text: 'Search LAX → NRT flights', link: `/en/flights/lax-nrt` },
      { type: 'h2', text: '💡 Pro Tips for Finding Cheap Flights from LAX' },
      { type: 'ul', items: [
        'Book 2-3 months ahead for domestic, 3-5 months for international',
        'Fly on Tuesdays and Wednesdays — consistently cheapest days',
        'Use flexible dates — shifting by 1-2 days can save 30-50%',
        'Consider nearby airports: Burbank (BUR), Long Beach (LGB), Ontario (ONT)',
        'Set up price alerts to catch flash sales',
      ]},
      { type: 'p', text: 'Start your search now and find the best deals from Los Angeles!' },
    ],
    content_ru: [
      { type: 'p', text: 'Международный аэропорт Лос-Анджелеса (LAX) — один из самых загруженных хабов в США, что означает невероятную конкуренцию между авиакомпаниями и отличные цены для путешественников. Вот самые дешёвые направления из LAX в 2026 году.' },
      { type: 'h2', text: '1. Сан-Франциско (SFO) — от $24' },
      { type: 'p', text: 'Короткий перелёт в Сан-Франциско — один из самых дешёвых внутренних маршрутов. Лоукостеры вроде Frontier (F9) предлагают прямые рейсы от $24. Лучше бронировать за 2-3 недели.' },
      { type: 'cta', text: 'Искать рейсы LAX → SFO', link: `/ru/flights/lax-sfo` },
      { type: 'h2', text: '2. Нью-Йорк (JFK) — от $102' },
      { type: 'p', text: 'Перелёт через всю страну в NYC начинается от $102 с пересадкой. Прямые рейсы JetBlue и American Airlines в среднем $125-180. Вторник — самый дешёвый день.' },
      { type: 'cta', text: 'Искать рейсы LAX → JFK', link: `/ru/flights/lax-jfk` },
      { type: 'h2', text: '3. Лас-Вегас (LAS) — от $29' },
      { type: 'p', text: 'Классический уикенд. Spirit и Frontier доминируют на этом маршруте с ценами ниже $30. Часовой перелёт идеален для спонтанных поездок.' },
      { type: 'h2', text: '4. Сиэтл (SEA) — от $49' },
      { type: 'p', text: 'Alaska Airlines и лоукостеры конкурируют на этом маршруте. Лучшие цены в межсезон (апрель-май, сентябрь-октябрь).' },
      { type: 'h2', text: '5. Канкун (CUN) — от $150' },
      { type: 'p', text: 'Мексиканский пляжный рай удивительно доступен из Лос-Анджелеса. Volaris и VivaAerobus предлагают самые низкие цены. В несезон (май-ноябрь) цены от $150 туда-обратно.' },
      { type: 'cta', text: 'Искать рейсы LAX → CUN', link: `/ru/flights/lax-cun` },
      { type: 'h2', text: '6. Токио (NRT) — от $450' },
      { type: 'p', text: 'Из LAX больше всего рейсов в Японию. ANA и JAL предлагают конкурентные цены, особенно в январе-марте (кроме праздников).' },
      { type: 'cta', text: 'Искать рейсы LAX → NRT', link: `/ru/flights/lax-nrt` },
      { type: 'h2', text: '💡 Советы по поиску дешёвых билетов из LAX' },
      { type: 'ul', items: [
        'Бронируйте за 2-3 месяца для внутренних, 3-5 для международных рейсов',
        'Летайте по вторникам и средам — стабильно самые дешёвые дни',
        'Используйте гибкие даты — сдвиг на 1-2 дня экономит 30-50%',
        'Рассмотрите соседние аэропорты: Burbank (BUR), Long Beach (LGB), Ontario (ONT)',
        'Настройте уведомления о ценах для отлова распродаж',
      ]},
      { type: 'p', text: 'Начните поиск сейчас и найдите лучшие предложения из Лос-Анджелеса!' },
    ],
  },
  {
    slug: 'moscow-istanbul-cheap-flights-guide',
    date: '2026-03-06',
    image: '🕌',
    title_en: 'Moscow to Istanbul: Complete Cheap Flights Guide',
    title_ru: 'Москва — Стамбул: полный гид по дешёвым билетам',
    desc_en: 'How to find the cheapest flights from Moscow to Istanbul. Best airlines, seasons, and booking tips.',
    desc_ru: 'Как найти самые дешёвые билеты Москва-Стамбул. Лучшие авиакомпании, сезоны и советы.',
    tags: ['flights', 'Moscow', 'Istanbul'],
    content_en: [
      { type: 'p', text: 'Istanbul has become one of the most popular destinations from Moscow. With multiple daily flights and competition between Turkish and Russian carriers, prices can be surprisingly low if you know when and how to book.' },
      { type: 'h2', text: 'Best Airlines for Moscow → Istanbul' },
      { type: 'ul', items: [
        'Turkish Airlines — best service, direct flights, 3-3.5 hours',
        'Pegasus Airlines — budget option, often 40-60% cheaper',
        'Aeroflot — direct flights from Sheremetyevo (SVO)',
        'Nordwind — seasonal charter flights at great prices',
      ]},
      { type: 'h2', text: 'When to Book for Best Prices' },
      { type: 'p', text: 'The cheapest time to fly Moscow-Istanbul is November through March (excluding New Year holidays). Summer (June-August) is peak season with prices 2-3x higher. Book 6-8 weeks in advance for the sweet spot.' },
      { type: 'h2', text: 'Price Guide' },
      { type: 'ul', items: [
        'Low season (Nov-Mar): $100-180 round trip',
        'Shoulder season (Apr-May, Sep-Oct): $150-250',
        'High season (Jun-Aug): $250-400',
        'New Year / holidays: $350-500+',
      ]},
      { type: 'cta', text: 'Search SVO → IST flights now', link: `/en/flights/svo-ist` },
      { type: 'h2', text: 'Where to Stay in Istanbul on a Budget' },
      { type: 'p', text: 'Sultanahmet and Fatih are the best areas for budget travelers — close to major attractions with hotels from $30/night. Beyoğlu/Taksim is more modern and lively, with mid-range options from $50/night.' },
      { type: 'cta-hotel', text: 'Find hotels in Istanbul', city: 'Istanbul' },
      { type: 'h2', text: '💡 Money-Saving Tips' },
      { type: 'ul', items: [
        'Fly on weekdays — weekend flights are 20-30% more expensive',
        'Consider Sabiha Gökçen Airport (SAW) instead of Istanbul Airport (IST) — often cheaper',
        'Use Istanbul Kart for public transport — much cheaper than taxis',
        'Book hotels in Laleli or Aksaray for best value',
      ]},
    ],
    content_ru: [
      { type: 'p', text: 'Стамбул стал одним из самых популярных направлений из Москвы. Множество ежедневных рейсов и конкуренция между турецкими и российскими перевозчиками позволяют найти отличные цены.' },
      { type: 'h2', text: 'Лучшие авиакомпании Москва → Стамбул' },
      { type: 'ul', items: [
        'Turkish Airlines — лучший сервис, прямые рейсы, 3-3.5 часа',
        'Pegasus Airlines — бюджетный вариант, часто на 40-60% дешевле',
        'Аэрофлот — прямые рейсы из Шереметьево (SVO)',
        'Nordwind — сезонные чартеры по отличным ценам',
      ]},
      { type: 'h2', text: 'Когда бронировать для лучших цен' },
      { type: 'p', text: 'Самое дешёвое время для перелёта Москва-Стамбул — с ноября по март (кроме новогодних праздников). Летом (июнь-август) — пик сезона, цены в 2-3 раза выше. Бронируйте за 6-8 недель — оптимальный момент.' },
      { type: 'h2', text: 'Гид по ценам' },
      { type: 'ul', items: [
        'Низкий сезон (ноя-мар): $100-180 туда-обратно',
        'Межсезон (апр-май, сен-окт): $150-250',
        'Высокий сезон (июн-авг): $250-400',
        'Новый год / праздники: $350-500+',
      ]},
      { type: 'cta', text: 'Искать рейсы SVO → IST', link: `/ru/flights/svo-ist` },
      { type: 'h2', text: 'Где жить в Стамбуле бюджетно' },
      { type: 'p', text: 'Султанахмет и Фатих — лучшие районы для бюджетных путешественников. Близко к достопримечательностям, отели от $30/ночь. Бейоглу/Таксим — более современный район с отелями от $50/ночь.' },
      { type: 'cta-hotel', text: 'Найти отели в Стамбуле', city: 'Istanbul' },
      { type: 'h2', text: '💡 Советы по экономии' },
      { type: 'ul', items: [
        'Летайте в будни — выходные на 20-30% дороже',
        'Рассмотрите аэропорт Сабиха Гёкчен (SAW) вместо Istanbul Airport (IST) — часто дешевле',
        'Используйте Istanbulkart для транспорта — намного дешевле такси',
        'Бронируйте отели в районах Лалели или Аксарай — лучшее соотношение цена/качество',
      ]},
    ],
  },
  {
    slug: 'best-budget-hotels-tips',
    date: '2026-03-06',
    image: '🏨',
    title_en: '10 Tips to Find the Cheapest Hotels Anywhere',
    title_ru: '10 советов как найти самые дешёвые отели',
    desc_en: 'Proven strategies to save 30-50% on hotel bookings. Compare platforms, use timing tricks, and more.',
    desc_ru: 'Проверенные стратегии экономии 30-50% на бронировании отелей. Сравнение платформ, тайминг и другие хитрости.',
    tags: ['hotels', 'budget', 'tips'],
    content_en: [
      { type: 'p', text: 'Hotels are often the biggest travel expense — bigger than flights. But with the right approach, you can cut your hotel costs by 30-50%. Here are 10 proven strategies.' },
      { type: 'h2', text: '1. Compare Multiple Platforms' },
      { type: 'p', text: 'Never book on the first site you check. Prices for the same room can vary 20-40% between platforms. Always compare at least Booking.com and one aggregator like Hotellook.' },
      { type: 'cta-hotel', text: 'Compare hotel prices', city: 'New York' },
      { type: 'h2', text: '2. Book 3-6 Weeks in Advance' },
      { type: 'p', text: 'Too early = high prices (hotels haven\'t started competing yet). Too late = limited options. The sweet spot is 3-6 weeks before your trip.' },
      { type: 'h2', text: '3. Stay on Weekdays' },
      { type: 'p', text: 'Business hotels are cheaper on weekends, tourist hotels are cheaper on weekdays. Know which type your hotel is and plan accordingly.' },
      { type: 'h2', text: '4. Look Beyond the City Center' },
      { type: 'p', text: 'Hotels 15-20 minutes from the center can be 50% cheaper. If public transport is good (Tokyo, London, Paris), this is a no-brainer.' },
      { type: 'h2', text: '5. Use Hotel Loyalty Programs' },
      { type: 'p', text: 'Even free tiers give you 10-15% discounts and perks like free breakfast and late checkout. Sign up before booking.' },
      { type: 'h2', text: '6. Check for Free Cancellation' },
      { type: 'p', text: 'Book a refundable rate first, then keep looking for better deals. If you find one, cancel the first booking.' },
      { type: 'h2', text: '7. Consider Apartments for 3+ Nights' },
      { type: 'p', text: 'For longer stays, apartments on Booking.com are often 30-40% cheaper per night than hotels, plus you save on food with a kitchen.' },
      { type: 'h2', text: '8. Travel in Shoulder Season' },
      { type: 'p', text: 'April-May and September-October offer the best combo: good weather + low hotel prices. Avoid school holidays.' },
      { type: 'h2', text: '9. Contact Hotels Directly' },
      { type: 'p', text: 'Some hotels offer better rates if you book directly (they save on platform commissions). Always worth checking their website.' },
      { type: 'h2', text: '10. Use Price Alerts' },
      { type: 'p', text: 'Set up alerts on comparison sites. Hotel prices fluctuate daily — catching a price drop can save you 20% or more.' },
      { type: 'p', text: 'Start comparing prices now and find the best deals for your next trip!' },
    ],
    content_ru: [
      { type: 'p', text: 'Отели — часто самая большая статья расходов в путешествии, даже больше авиабилетов. Но с правильным подходом можно сэкономить 30-50%. Вот 10 проверенных стратегий.' },
      { type: 'h2', text: '1. Сравнивайте несколько платформ' },
      { type: 'p', text: 'Никогда не бронируйте на первом попавшемся сайте. Цены на один и тот же номер могут отличаться на 20-40%. Всегда сравнивайте Booking.com и агрегатор вроде Hotellook.' },
      { type: 'cta-hotel', text: 'Сравнить цены на отели', city: 'New York' },
      { type: 'h2', text: '2. Бронируйте за 3-6 недель' },
      { type: 'p', text: 'Слишком рано = высокие цены (отели ещё не начали конкурировать). Слишком поздно = мало вариантов. Оптимум — 3-6 недель до поездки.' },
      { type: 'h2', text: '3. Останавливайтесь в будни' },
      { type: 'p', text: 'Бизнес-отели дешевле на выходных, туристические — в будни. Определите тип и планируйте соответственно.' },
      { type: 'h2', text: '4. Смотрите за пределами центра' },
      { type: 'p', text: 'Отели в 15-20 минутах от центра могут быть на 50% дешевле. Если транспорт хороший (Токио, Лондон, Париж) — это очевидный выбор.' },
      { type: 'h2', text: '5. Используйте программы лояльности' },
      { type: 'p', text: 'Даже бесплатные уровни дают скидку 10-15% и бонусы вроде бесплатного завтрака. Регистрируйтесь перед бронированием.' },
      { type: 'h2', text: '6. Проверяйте бесплатную отмену' },
      { type: 'p', text: 'Бронируйте возвратный тариф, потом ищите дешевле. Нашли — отменяйте первое бронирование.' },
      { type: 'h2', text: '7. Рассмотрите апартаменты (3+ ночей)' },
      { type: 'p', text: 'Для длительных поездок апартаменты на Booking.com на 30-40% дешевле отелей за ночь, плюс кухня экономит на еде.' },
      { type: 'h2', text: '8. Путешествуйте в межсезон' },
      { type: 'p', text: 'Апрель-май и сентябрь-октябрь — лучший баланс: хорошая погода + низкие цены на отели. Избегайте школьных каникул.' },
      { type: 'h2', text: '9. Бронируйте напрямую у отелей' },
      { type: 'p', text: 'Некоторые отели дают лучшие цены при прямом бронировании (экономят на комиссии платформ). Всегда стоит проверить их сайт.' },
      { type: 'h2', text: '10. Настройте уведомления о ценах' },
      { type: 'p', text: 'Цены на отели меняются ежедневно — поймать падение цены = экономия 20% и больше.' },
      { type: 'p', text: 'Начните сравнивать цены и найдите лучшие предложения для следующей поездки!' },
    ],
  },
  {
    slug: 'new-york-travel-guide-budget',
    date: '2026-03-06',
    image: '🗽',
    title_en: 'New York on a Budget: Complete 2026 Guide',
    title_ru: 'Нью-Йорк бюджетно: полный гид 2026',
    desc_en: 'How to visit NYC without going broke. Cheap flights, affordable hotels, free attractions, and food tips.',
    desc_ru: 'Как посетить Нью-Йорк и не разориться. Дешёвые билеты, доступные отели, бесплатные достопримечательности.',
    tags: ['New York', 'budget', 'guide'],
    content_en: [
      { type: 'p', text: 'New York City has a reputation for being expensive — and it can be. But with the right planning, you can experience the Big Apple on a surprisingly modest budget. Here\'s your complete guide.' },
      { type: 'h2', text: '✈️ Getting There Cheap' },
      { type: 'p', text: 'JFK, Newark (EWR), and LaGuardia (LGA) all serve NYC. Budget carriers like Spirit, Frontier, and JetBlue often have the best deals. Cross-country flights from LAX start at just $102.' },
      { type: 'cta', text: 'Search flights to New York', link: `/en/flights/lax-jfk` },
      { type: 'h2', text: '🏨 Where to Stay ($30-80/night)' },
      { type: 'p', text: 'Manhattan is pricey, but look at Brooklyn (Williamsburg, Bushwick) or Queens (Astoria, Long Island City) for hotels 40-60% cheaper. Hostels start at $30/night, budget hotels at $60-80.' },
      { type: 'cta-hotel', text: 'Find budget hotels in NYC', city: 'New York' },
      { type: 'h2', text: '🎭 Free Things to Do' },
      { type: 'ul', items: [
        'Central Park — walk, bike, people-watch (free)',
        'Brooklyn Bridge — iconic walk with skyline views',
        'Staten Island Ferry — free views of Statue of Liberty',
        'Times Square — the experience is free (the shopping isn\'t)',
        'Museums: MoMA (Friday evenings), Met Museum (pay-what-you-wish for NY residents)',
        'High Line — elevated park with amazing architecture',
        'Grand Central Terminal — stunning Beaux-Arts architecture',
      ]},
      { type: 'h2', text: '🍕 Eating Cheap in NYC' },
      { type: 'ul', items: [
        '$1 pizza slices still exist — Joe\'s Pizza, 2 Bros, NY Pizza Suprema',
        'Halal carts — $5-7 for a huge chicken-over-rice plate',
        'Chinatown — dumplings for $3-5, noodle soups for $8',
        'Bagels — $2-4 for a proper NYC bagel',
        'Happy hours — half-price drinks and apps, 4-7pm in most bars',
      ]},
      { type: 'h2', text: '🚇 Getting Around' },
      { type: 'p', text: 'Get an OMNY or MetroCard — $2.90/ride, $34 for unlimited weekly. NYC subway goes everywhere. Skip taxis and Ubers unless it\'s late night.' },
      { type: 'h2', text: '💰 Sample Daily Budget' },
      { type: 'ul', items: [
        'Accommodation: $50-80 (budget hotel/hostel)',
        'Food: $25-40 (street food + one sit-down meal)',
        'Transport: $7-10 (subway)',
        'Activities: $0-20 (mostly free attractions)',
        'Total: $82-150/day',
      ]},
      { type: 'p', text: 'That\'s $575-1050 for a week in New York City — very doable!' },
    ],
    content_ru: [
      { type: 'p', text: 'Нью-Йорк слывёт дорогим городом — и это правда. Но с правильным планированием можно посетить Большое Яблоко на удивительно скромном бюджете. Вот полный гид.' },
      { type: 'h2', text: '✈️ Как добраться дёшево' },
      { type: 'p', text: 'NYC обслуживают JFK, Newark (EWR) и LaGuardia (LGA). Лоукостеры Spirit, Frontier и JetBlue часто предлагают лучшие цены. Перелёт из LAX — от $102.' },
      { type: 'cta', text: 'Искать рейсы в Нью-Йорк', link: `/ru/flights/lax-jfk` },
      { type: 'h2', text: '🏨 Где жить ($30-80/ночь)' },
      { type: 'p', text: 'Манхэттен дорогой, но Бруклин (Williamsburg, Bushwick) или Квинс (Astoria, Long Island City) на 40-60% дешевле. Хостелы от $30/ночь, бюджетные отели $60-80.' },
      { type: 'cta-hotel', text: 'Найти бюджетные отели в NYC', city: 'New York' },
      { type: 'h2', text: '🎭 Бесплатные развлечения' },
      { type: 'ul', items: [
        'Центральный парк — прогулки, велосипеды (бесплатно)',
        'Бруклинский мост — культовая прогулка с видом на скайлайн',
        'Паром Staten Island — бесплатный вид на Статую Свободы',
        'Таймс-Сквер — опыт бесплатный (шоппинг — нет)',
        'Музеи: MoMA (пятница вечером), Метрополитен (pay-what-you-wish)',
        'Хай-Лайн — парк на старой ж/д эстакаде',
        'Гранд Сентрал — потрясающая архитектура',
      ]},
      { type: 'h2', text: '🍕 Дешёвая еда в NYC' },
      { type: 'ul', items: [
        'Пицца за $1 — Joe\'s Pizza, 2 Bros, NY Pizza Suprema',
        'Халяль-тележки — $5-7 за огромную порцию курицы с рисом',
        'Чайнатаун — пельмени $3-5, суп-лапша $8',
        'Бейглы — $2-4 за настоящий нью-йоркский бейгл',
        'Happy hours — полцены на напитки и закуски, 16-19',
      ]},
      { type: 'h2', text: '🚇 Транспорт' },
      { type: 'p', text: 'MetroCard или OMNY — $2.90/поездка, $34 за безлимитный на неделю. Метро идёт везде. Такси и Uber только ночью.' },
      { type: 'h2', text: '💰 Примерный бюджет на день' },
      { type: 'ul', items: [
        'Жильё: $50-80 (бюджетный отель/хостел)',
        'Еда: $25-40 (стрит-фуд + один ресторан)',
        'Транспорт: $7-10 (метро)',
        'Развлечения: $0-20 (в основном бесплатно)',
        'Итого: $82-150/день',
      ]},
      { type: 'p', text: '$575-1050 за неделю в Нью-Йорке — вполне реально!' },
    ],
  },
  {
    slug: 'dubai-vs-istanbul-budget-travel',
    date: '2026-03-06',
    image: '🏙️',
    title_en: 'Dubai vs Istanbul: Which is Cheaper for Tourists in 2026?',
    title_ru: 'Дубай vs Стамбул: что дешевле для туристов в 2026?',
    desc_en: 'Head-to-head comparison of Dubai and Istanbul for budget travelers. Flights, hotels, food, and activities.',
    desc_ru: 'Сравнение Дубая и Стамбула для бюджетных путешественников. Билеты, отели, еда и развлечения.',
    tags: ['Dubai', 'Istanbul', 'comparison', 'budget'],
    content_en: [
      { type: 'p', text: 'Dubai and Istanbul are two of the most popular destinations for travelers from Russia, Europe, and the Middle East. But which one is more budget-friendly? Let\'s compare.' },
      { type: 'h2', text: '✈️ Flights' },
      { type: 'p', text: 'From Moscow, Istanbul wins hands-down. Direct flights SVO→IST cost $100-180 in low season. Dubai (SVO→DXB) is $200-350. Istanbul is closer (3h vs 5h) and has more competition.' },
      { type: 'cta', text: 'Compare: Moscow → Istanbul', link: `/en/flights/svo-ist` },
      { type: 'cta', text: 'Compare: Moscow → Dubai', link: `/en/flights/svo-dxb` },
      { type: 'h2', text: '🏨 Hotels' },
      { type: 'p', text: 'Istanbul is significantly cheaper. A good 3-star hotel in Istanbul: $30-50/night. Same level in Dubai: $70-120/night. Istanbul also has more hostels and budget options.' },
      { type: 'h2', text: '🍽️ Food' },
      { type: 'p', text: 'Istanbul: street food (döner, simit, balık ekmek) from $2-5. Restaurant meal: $8-15. Dubai: food courts from $7-12. Restaurant meal: $20-40. Istanbul wins by 2-3x.' },
      { type: 'h2', text: '🎯 Activities' },
      { type: 'p', text: 'Istanbul has more free attractions: Hagia Sophia (free), Blue Mosque (free), Grand Bazaar (free to browse). Dubai\'s top attractions cost money: Burj Khalifa ($40), Dubai Frame ($15), Desert Safari ($50).' },
      { type: 'h2', text: '💰 Daily Budget Comparison' },
      { type: 'ul', items: [
        'Istanbul budget: $50-80/day (hotel + food + transport + activities)',
        'Dubai budget: $120-200/day (hotel + food + transport + activities)',
        'Winner: Istanbul is 2-2.5x cheaper',
      ]},
      { type: 'h2', text: '🏆 Verdict' },
      { type: 'p', text: 'For budget travelers: Istanbul, no contest. For luxury seekers who want beaches and malls: Dubai. Both are amazing cities — Istanbul just lets you enjoy more for less.' },
      { type: 'cta-hotel', text: 'Hotels in Istanbul', city: 'Istanbul' },
      { type: 'cta-hotel', text: 'Hotels in Dubai', city: 'Dubai' },
    ],
    content_ru: [
      { type: 'p', text: 'Дубай и Стамбул — два самых популярных направления для путешественников из России. Но какой из них бюджетнее? Давайте сравним.' },
      { type: 'h2', text: '✈️ Перелёт' },
      { type: 'p', text: 'Из Москвы Стамбул побеждает. Прямые рейсы SVO→IST стоят $100-180 в низкий сезон. Дубай (SVO→DXB) — $200-350. Стамбул ближе (3ч vs 5ч) и больше конкуренция.' },
      { type: 'cta', text: 'Сравнить: Москва → Стамбул', link: `/ru/flights/svo-ist` },
      { type: 'cta', text: 'Сравнить: Москва → Дубай', link: `/ru/flights/svo-dxb` },
      { type: 'h2', text: '🏨 Отели' },
      { type: 'p', text: 'Стамбул значительно дешевле. Хороший 3-звёздочный отель: $30-50/ночь. Такой же в Дубае: $70-120/ночь. В Стамбуле больше хостелов и бюджетных вариантов.' },
      { type: 'h2', text: '🍽️ Еда' },
      { type: 'p', text: 'Стамбул: стрит-фуд (дёнер, симит, балык экмек) от $2-5. Ресторан: $8-15. Дубай: фуд-корты от $7-12. Ресторан: $20-40. Стамбул дешевле в 2-3 раза.' },
      { type: 'h2', text: '🎯 Развлечения' },
      { type: 'p', text: 'В Стамбуле больше бесплатных достопримечательностей: Айя-София (бесплатно), Голубая мечеть (бесплатно), Гранд Базар. В Дубае топ-аттракции платные: Бурдж-Халифа ($40), Dubai Frame ($15), сафари ($50).' },
      { type: 'h2', text: '💰 Бюджет на день' },
      { type: 'ul', items: [
        'Стамбул: $50-80/день (отель + еда + транспорт + развлечения)',
        'Дубай: $120-200/день (отель + еда + транспорт + развлечения)',
        'Победитель: Стамбул дешевле в 2-2.5 раза',
      ]},
      { type: 'h2', text: '🏆 Вердикт' },
      { type: 'p', text: 'Для бюджетных путешественников: Стамбул, без вариантов. Для любителей люкса, пляжей и моллов: Дубай. Оба города потрясающие — просто Стамбул позволяет получить больше за меньшие деньги.' },
      { type: 'cta-hotel', text: 'Отели в Стамбуле', city: 'Istanbul' },
      { type: 'cta-hotel', text: 'Отели в Дубае', city: 'Dubai' },
    ],
  },
];

export function getPost(slug) {
  return BLOG_POSTS.find((p) => p.slug === slug) || null;
}
