/**
 * Popular routes for SEO landing pages and internal linking.
 * Each entry: { from, to, fromCity_ru, toCity_ru, fromCity_en, toCity_en, tips_ru, tips_en }
 */
export const POPULAR_ROUTES = [
  // ===== US DOMESTIC (40 routes) =====
  { from: 'LAX', to: 'JFK', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Нью-Йорк', fromCity_en: 'Los Angeles', toCity_en: 'New York',
    tips_ru: ['Лучшие цены за 2-3 месяца до вылета', 'Вторник и среда — самые дешёвые дни', 'Рассмотри рейсы с пересадкой — экономия до 40%'],
    tips_en: ['Best prices 2-3 months before departure', 'Tuesday and Wednesday are cheapest', 'Consider connecting flights — save up to 40%'] },
  { from: 'JFK', to: 'LAX', fromCity_ru: 'Нью-Йорк', toCity_ru: 'Лос-Анджелес', fromCity_en: 'New York', toCity_en: 'Los Angeles',
    tips_ru: ['Ночные рейсы обычно дешевле', 'Проверь Newark (EWR) — часто дешевле JFK', 'JetBlue часто предлагает лучший баланс цены и комфорта'],
    tips_en: ['Red-eye flights are usually cheaper', 'Check Newark (EWR) — often cheaper than JFK', 'JetBlue often offers best price-comfort balance'] },
  { from: 'LAX', to: 'SFO', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Сан-Франциско', fromCity_en: 'Los Angeles', toCity_en: 'San Francisco',
    tips_ru: ['Короткий перелёт — лоукостеры часто дешевле', 'Рассмотри Oakland (OAK) как альтернативу SFO'],
    tips_en: ['Short flight — budget airlines often cheaper', 'Consider Oakland (OAK) as alternative to SFO'] },
  { from: 'SFO', to: 'LAX', fromCity_ru: 'Сан-Франциско', toCity_ru: 'Лос-Анджелес', fromCity_en: 'San Francisco', toCity_en: 'Los Angeles',
    tips_ru: ['Бронируй за неделю — дешевле чем last minute', 'Burbank (BUR) часто удобнее LAX'],
    tips_en: ['Book a week ahead — cheaper than last minute', 'Burbank (BUR) often more convenient than LAX'] },
  { from: 'SFO', to: 'SEA', fromCity_ru: 'Сан-Франциско', toCity_ru: 'Сиэтл', fromCity_en: 'San Francisco', toCity_en: 'Seattle',
    tips_ru: ['Alaska Airlines часто имеет лучшие цены', 'Раннее утро — самые дешёвые рейсы'],
    tips_en: ['Alaska Airlines often has the best prices', 'Early morning flights are cheapest'] },
  { from: 'SEA', to: 'SFO', fromCity_ru: 'Сиэтл', toCity_ru: 'Сан-Франциско', fromCity_en: 'Seattle', toCity_en: 'San Francisco',
    tips_ru: ['Пятница вечером — дороже, лети в субботу', 'Southwest не показывается в поиске — проверь их сайт'],
    tips_en: ['Friday evening is pricey, fly Saturday instead', 'Southwest doesn\'t show in search — check their site'] },
  { from: 'LAX', to: 'MIA', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Майами', fromCity_en: 'Los Angeles', toCity_en: 'Miami',
    tips_ru: ['Зимой цены выше — бронируй заранее', 'Spirit и Frontier — самые дешёвые опции'],
    tips_en: ['Prices higher in winter — book early', 'Spirit and Frontier are cheapest options'] },
  { from: 'MIA', to: 'LAX', fromCity_ru: 'Майами', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Miami', toCity_en: 'Los Angeles',
    tips_ru: ['С пересадкой в Dallas экономия 30-40%', 'Июнь-сентябрь — низкий сезон, хорошие цены'],
    tips_en: ['Connecting via Dallas saves 30-40%', 'June-September is low season with good prices'] },
  { from: 'ORD', to: 'LAX', fromCity_ru: 'Чикаго', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Chicago', toCity_en: 'Los Angeles',
    tips_ru: ['Midway (MDW) может быть дешевле O\'Hare', 'American и United конкурируют — сравни цены'],
    tips_en: ['Midway (MDW) can be cheaper than O\'Hare', 'American and United compete — compare prices'] },
  { from: 'LAX', to: 'ORD', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Чикаго', fromCity_en: 'Los Angeles', toCity_en: 'Chicago',
    tips_ru: ['Зима в Чикаго холодная — возможны задержки рейсов', 'Вылет в 6 утра — на 20-30% дешевле'],
    tips_en: ['Chicago winters are cold — possible flight delays', '6 AM departure is 20-30% cheaper'] },
  { from: 'ATL', to: 'LAX', fromCity_ru: 'Атланта', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Atlanta', toCity_en: 'Los Angeles',
    tips_ru: ['Delta доминирует в Атланте — часто лучшие цены', 'Прямые рейсы выгоднее пересадок на этом маршруте'],
    tips_en: ['Delta dominates Atlanta — often best prices', 'Direct flights better value than connections on this route'] },
  { from: 'LAX', to: 'ATL', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Атланта', fromCity_en: 'Los Angeles', toCity_en: 'Atlanta',
    tips_ru: ['Среда и суббота — самые дешёвые дни для вылета', 'SkyMiles от Delta накапливаются быстро'],
    tips_en: ['Wednesday and Saturday are cheapest departure days', 'Delta SkyMiles accumulate quickly'] },
  { from: 'DFW', to: 'LAX', fromCity_ru: 'Даллас', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Dallas', toCity_en: 'Los Angeles',
    tips_ru: ['American Airlines hub — лучший выбор', 'Love Field (DAL) с Southwest дешевле'],
    tips_en: ['American Airlines hub — best choice', 'Love Field (DAL) with Southwest is cheaper'] },
  { from: 'LAX', to: 'DFW', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Даллас', fromCity_en: 'Los Angeles', toCity_en: 'Dallas',
    tips_ru: ['Короткий перелёт 2.5 часа — комфортно', 'Вечерние рейсы дешевле утренних'],
    tips_en: ['Short 2.5 hour flight — comfortable', 'Evening flights cheaper than morning'] },
  { from: 'JFK', to: 'MIA', fromCity_ru: 'Нью-Йорк', toCity_ru: 'Майами', fromCity_en: 'New York', toCity_en: 'Miami',
    tips_ru: ['Очень популярный маршрут — бронируй за месяц', 'Fort Lauderdale (FLL) дешевле чем MIA'],
    tips_en: ['Very popular route — book a month ahead', 'Fort Lauderdale (FLL) cheaper than MIA'] },
  { from: 'MIA', to: 'JFK', fromCity_ru: 'Майами', toCity_ru: 'Нью-Йорк', fromCity_en: 'Miami', toCity_en: 'New York',
    tips_ru: ['Зимой все летят в Майами — цены высокие', 'JetBlue Mint для бизнес-класса — отличная цена'],
    tips_en: ['Everyone flies to Miami in winter — high prices', 'JetBlue Mint for business class — great value'] },
  { from: 'JFK', to: 'SFO', fromCity_ru: 'Нью-Йорк', toCity_ru: 'Сан-Франциско', fromCity_en: 'New York', toCity_en: 'San Francisco',
    tips_ru: ['6 часов полёта — возьми еду в самолёт', 'Ночной рейс позволяет поспать и сэкономить отель'],
    tips_en: ['6 hour flight — bring food', 'Red-eye lets you sleep and saves a hotel night'] },
  { from: 'SFO', to: 'JFK', fromCity_ru: 'Сан-Франциско', toCity_ru: 'Нью-Йорк', fromCity_en: 'San Francisco', toCity_en: 'New York',
    tips_ru: ['Разница в 3 часа — прилёт поздно вечером', 'Virgin America (теперь Alaska) — хороший комфорт'],
    tips_en: ['3 hour time difference — arrive late evening', 'Virgin America (now Alaska) — good comfort'] },
  { from: 'DEN', to: 'LAX', fromCity_ru: 'Денвер', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Denver', toCity_en: 'Los Angeles',
    tips_ru: ['Southwest и Frontier базируются в Денвере — хорошие цены', 'Зимой возможны задержки из-за снега'],
    tips_en: ['Southwest and Frontier are based in Denver — good prices', 'Winter delays possible due to snow'] },
  { from: 'LAX', to: 'DEN', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Денвер', fromCity_en: 'Los Angeles', toCity_en: 'Denver',
    tips_ru: ['Горнолыжный сезон — цены выше в декабре-марте', 'United и Southwest — основные перевозчики'],
    tips_en: ['Ski season — prices higher Dec-March', 'United and Southwest are main carriers'] },
  { from: 'BOS', to: 'LAX', fromCity_ru: 'Бостон', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Boston', toCity_en: 'Los Angeles',
    tips_ru: ['Длинный перелёт 5.5 часов — бронируй место заранее', 'Зимой вылеты из Бостона часто задерживают'],
    tips_en: ['Long 5.5 hour flight — book seat in advance', 'Winter departures from Boston often delayed'] },
  { from: 'LAX', to: 'BOS', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Бостон', fromCity_en: 'Los Angeles', toCity_en: 'Boston',
    tips_ru: ['Прилёт поздно вечером — планируй трансфер заранее', 'JetBlue — хороший баланс цены и комфорта'],
    tips_en: ['Late evening arrival — plan transfer ahead', 'JetBlue — good price-comfort balance'] },
  { from: 'LAX', to: 'LAS', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Лас-Вегас', fromCity_en: 'Los Angeles', toCity_en: 'Las Vegas',
    tips_ru: ['Очень короткий перелёт 1 час — дешевле ехать?', 'Spirit от $29 в будни — проверяй багаж отдельно'],
    tips_en: ['Very short 1 hour flight — cheaper to drive?', 'Spirit from $29 on weekdays — check baggage separately'] },
  { from: 'LAS', to: 'LAX', fromCity_ru: 'Лас-Вегас', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Las Vegas', toCity_en: 'Los Angeles',
    tips_ru: ['Воскресенье вечером — самый дорогой день', 'Понедельник утром — на 50% дешевле'],
    tips_en: ['Sunday evening is most expensive day', 'Monday morning is 50% cheaper'] },
  { from: 'PHX', to: 'LAX', fromCity_ru: 'Финикс', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Phoenix', toCity_en: 'Los Angeles',
    tips_ru: ['American Airlines — основной перевозчик', 'Летом в Фениксе жара — рейсы могут отменять'],
    tips_en: ['American Airlines is main carrier', 'Summer Phoenix heat can cause cancellations'] },
  { from: 'LAX', to: 'PHX', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Финикс', fromCity_en: 'Los Angeles', toCity_en: 'Phoenix',
    tips_ru: ['Короткий час полёта — не нужна еда', 'Southwest не взимает плату за багаж'],
    tips_en: ['Short one hour flight — no meal needed', 'Southwest doesn\'t charge for bags'] },
  { from: 'SAN', to: 'SFO', fromCity_ru: 'Сан-Диего', toCity_ru: 'Сан-Франциско', fromCity_en: 'San Diego', toCity_en: 'San Francisco',
    tips_ru: ['Alaska Airlines — лучший выбор', 'Раннее бронирование экономит 40%'],
    tips_en: ['Alaska Airlines is best choice', 'Early booking saves 40%'] },
  { from: 'SFO', to: 'SAN', fromCity_ru: 'Сан-Франциско', toCity_ru: 'Сан-Диего', fromCity_en: 'San Francisco', toCity_en: 'San Diego',
    tips_ru: ['Southwest летает часто — гибкий выбор времени', 'Лето в Сан-Диего — идеальная погода'],
    tips_en: ['Southwest flies frequently — flexible timing', 'Summer in San Diego — perfect weather'] },
  { from: 'PDX', to: 'LAX', fromCity_ru: 'Портленд', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Portland', toCity_en: 'Los Angeles',
    tips_ru: ['Alaska Airlines доминирует на маршруте', 'Зимой в Портленде часто дожди — проверь погоду'],
    tips_en: ['Alaska Airlines dominates route', 'Portland winters rainy — check weather'] },
  { from: 'LAX', to: 'PDX', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Портленд', fromCity_en: 'Los Angeles', toCity_en: 'Portland',
    tips_ru: ['2.5 часа полёта — комфортный перелёт', 'Дешевле всего по вторникам'],
    tips_en: ['2.5 hour flight — comfortable journey', 'Cheapest on Tuesdays'] },
  { from: 'IAH', to: 'LAX', fromCity_ru: 'Хьюстон', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Houston', toCity_en: 'Los Angeles',
    tips_ru: ['United Airlines hub в Хьюстоне', 'Hobby Airport (HOU) с Southwest дешевле'],
    tips_en: ['United Airlines hub in Houston', 'Hobby Airport (HOU) with Southwest is cheaper'] },
  { from: 'LAX', to: 'IAH', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Хьюстон', fromCity_en: 'Los Angeles', toCity_en: 'Houston',
    tips_ru: ['Прямой рейс 3 часа — без пересадок удобнее', 'Летом в Хьюстоне очень влажно'],
    tips_en: ['Direct flight 3 hours — no connections easier', 'Houston summers are very humid'] },
  { from: 'SEA', to: 'LAX', fromCity_ru: 'Сиэтл', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Seattle', toCity_en: 'Los Angeles',
    tips_ru: ['Alaska Airlines — лучший выбор для West Coast', 'Вылет рано утром — избегай опозданий'],
    tips_en: ['Alaska Airlines best for West Coast', 'Early morning departure avoids delays'] },
  { from: 'MSP', to: 'LAX', fromCity_ru: 'Миннеаполис', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Minneapolis', toCity_en: 'Los Angeles',
    tips_ru: ['Delta hub в Minneapolis — хорошие цены', 'Зимой возможны отмены из-за снегопадов'],
    tips_en: ['Delta hub in Minneapolis — good prices', 'Winter cancellations possible due to snow'] },
  { from: 'LAX', to: 'MSP', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Миннеаполис', fromCity_en: 'Los Angeles', toCity_en: 'Minneapolis',
    tips_ru: ['Прямой рейс 3.5 часа', 'Sun Country Airlines — бюджетная опция'],
    tips_en: ['Direct flight 3.5 hours', 'Sun Country Airlines is budget option'] },
  { from: 'DTW', to: 'LAX', fromCity_ru: 'Детройт', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Detroit', toCity_en: 'Los Angeles',
    tips_ru: ['Delta доминирует в Детройте', 'Spirit Airlines — дешёвая альтернатива'],
    tips_en: ['Delta dominates Detroit', 'Spirit Airlines is cheap alternative'] },
  { from: 'LAX', to: 'DTW', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Детройт', fromCity_en: 'Los Angeles', toCity_en: 'Detroit',
    tips_ru: ['Около 4 часов полёта', 'Зимой в Детройте холодно — тёплая одежда'],
    tips_en: ['About 4 hours flight time', 'Detroit winters cold — warm clothes'] },
  { from: 'PHL', to: 'LAX', fromCity_ru: 'Филадельфия', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Philadelphia', toCity_en: 'Los Angeles',
    tips_ru: ['American Airlines hub', 'Ночные рейсы значительно дешевле'],
    tips_en: ['American Airlines hub', 'Red-eyes significantly cheaper'] },
  { from: 'LAX', to: 'PHL', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Филадельфия', fromCity_en: 'Los Angeles', toCity_en: 'Philadelphia',
    tips_ru: ['5+ часов полёта — возьми развлечения', 'Прилёт поздно вечером — планируй трансфер'],
    tips_en: ['5+ hour flight — bring entertainment', 'Late evening arrival — plan transfer'] },
  { from: 'CLT', to: 'LAX', fromCity_ru: 'Шарлотт', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Charlotte', toCity_en: 'Los Angeles',
    tips_ru: ['American Airlines второй по величине hub', 'Прямые рейсы выгоднее пересадок'],
    tips_en: ['American Airlines second largest hub', 'Direct flights better value than connections'] },
  { from: 'LAX', to: 'CLT', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Шарлотт', fromCity_en: 'Los Angeles', toCity_en: 'Charlotte',
    tips_ru: ['4.5 часа полёта через всю страну', 'Среда — самый дешёвый день'],
    tips_en: ['4.5 hour cross-country flight', 'Wednesday is cheapest day'] },

  // ===== US ↔ EUROPE (25 routes) =====
  { from: 'JFK', to: 'LHR', fromCity_ru: 'Нью-Йорк', toCity_ru: 'Лондон', fromCity_en: 'New York', toCity_en: 'London',
    tips_ru: ['Осень — лучшее время для дешёвых билетов', 'Norwegian и PLAY — бюджетные опции', 'Gatwick (LGW) дешевле Heathrow'],
    tips_en: ['Fall is best for cheap tickets', 'Norwegian and PLAY are budget options', 'Gatwick (LGW) cheaper than Heathrow'] },
  { from: 'LHR', to: 'JFK', fromCity_ru: 'Лондон', toCity_ru: 'Нью-Йорк', fromCity_en: 'London', toCity_en: 'New York',
    tips_ru: ['Virgin Atlantic часто проводит распродажи', 'Вылет утром позволяет прибыть днём в NY'],
    tips_en: ['Virgin Atlantic often has sales', 'Morning departure arrives afternoon in NY'] },
  { from: 'LAX', to: 'CDG', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Париж', fromCity_en: 'Los Angeles', toCity_en: 'Paris',
    tips_ru: ['Прямые рейсы Air France и Delta', 'С пересадкой в Исландии бывает дешевле', 'Бронируй за 3-4 месяца'],
    tips_en: ['Direct flights on Air France and Delta', 'Connecting via Iceland can be cheaper', 'Book 3-4 months ahead'] },
  { from: 'CDG', to: 'LAX', fromCity_ru: 'Париж', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Paris', toCity_en: 'Los Angeles',
    tips_ru: ['Прилёт вечером — весь день в дороге', 'French Bee — новый бюджетный перевозчик'],
    tips_en: ['Evening arrival — full day travel', 'French Bee is new budget carrier'] },
  { from: 'ORD', to: 'FRA', fromCity_ru: 'Чикаго', toCity_ru: 'Франкфурт', fromCity_en: 'Chicago', toCity_en: 'Frankfurt',
    tips_ru: ['Lufthansa — основной перевозчик', 'United из Chicago дешевле европейских авиакомпаний'],
    tips_en: ['Lufthansa is main carrier', 'United from Chicago cheaper than European airlines'] },
  { from: 'FRA', to: 'ORD', fromCity_ru: 'Франкфурт', toCity_ru: 'Чикаго', fromCity_en: 'Frankfurt', toCity_en: 'Chicago',
    tips_ru: ['Утренний вылет — прибытие днём', 'Hahn Airport (HHN) — бюджетная альтернатива'],
    tips_en: ['Morning departure — afternoon arrival', 'Hahn Airport (HHN) is budget alternative'] },
  { from: 'JFK', to: 'FCO', fromCity_ru: 'Нью-Йорк', toCity_ru: 'Рим', fromCity_en: 'New York', toCity_en: 'Rome',
    tips_ru: ['ITA Airways — наследник Alitalia', 'Весна и осень — идеальное время и хорошие цены'],
    tips_en: ['ITA Airways — successor to Alitalia', 'Spring and fall — ideal time and good prices'] },
  { from: 'FCO', to: 'JFK', fromCity_ru: 'Рим', toCity_ru: 'Нью-Йорк', fromCity_en: 'Rome', toCity_en: 'New York',
    tips_ru: ['Дневные рейсы удобнее ночных', 'Ciampino (CIA) с Ryanair для бюджета'],
    tips_en: ['Day flights more convenient than night', 'Ciampino (CIA) with Ryanair for budget'] },
  { from: 'BOS', to: 'LHR', fromCity_ru: 'Бостон', toCity_ru: 'Лондон', fromCity_en: 'Boston', toCity_en: 'London',
    tips_ru: ['Прямой рейс 6.5 часов', 'British Airways и American сотрудничают'],
    tips_en: ['Direct flight 6.5 hours', 'British Airways and American partner'] },
  { from: 'LHR', to: 'BOS', fromCity_ru: 'Лондон', toCity_ru: 'Бостон', fromCity_en: 'London', toCity_en: 'Boston',
    tips_ru: ['Вылет утром — прибытие в обед', 'JetBlue из BOS часто дешевле'],
    tips_en: ['Morning departure — lunch arrival', 'JetBlue from BOS often cheaper'] },
  { from: 'EWR', to: 'MAD', fromCity_ru: 'Ньюарк', toCity_ru: 'Мадрид', fromCity_en: 'Newark', toCity_en: 'Madrid',
    tips_ru: ['United hub в Newark — хорошие цены', 'Iberia — испанский флагман'],
    tips_en: ['United hub in Newark — good prices', 'Iberia is Spanish flagship'] },
  { from: 'MAD', to: 'EWR', fromCity_ru: 'Мадрид', toCity_ru: 'Ньюарк', fromCity_en: 'Madrid', toCity_en: 'Newark',
    tips_ru: ['8 часов прямого перелёта', 'Level Airlines — бюджетная дочка Iberia'],
    tips_en: ['8 hour direct flight', 'Level Airlines — Iberia budget subsidiary'] },
  { from: 'MIA', to: 'LHR', fromCity_ru: 'Майами', toCity_ru: 'Лондон', fromCity_en: 'Miami', toCity_en: 'London',
    tips_ru: ['American и British Airways партнёры', 'Лето в Майами — низкий сезон, дешевле'],
    tips_en: ['American and British Airways partners', 'Miami summer is low season, cheaper'] },
  { from: 'LAX', to: 'AMS', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Амстердам', fromCity_en: 'Los Angeles', toCity_en: 'Amsterdam',
    tips_ru: ['KLM прямой рейс 10 часов', 'Delta партнёр KLM — накапливай мили'],
    tips_en: ['KLM direct flight 10 hours', 'Delta partners with KLM — earn miles'] },
  { from: 'AMS', to: 'LAX', fromCity_ru: 'Амстердам', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Amsterdam', toCity_en: 'Los Angeles',
    tips_ru: ['Вылет днём — прилёт днём (через полночь)', 'Schiphol — удобный аэропорт для пересадок'],
    tips_en: ['Day departure — day arrival (overnight)', 'Schiphol is convenient for connections'] },
  { from: 'SFO', to: 'LHR', fromCity_ru: 'Сан-Франциско', toCity_ru: 'Лондон', fromCity_en: 'San Francisco', toCity_en: 'London',
    tips_ru: ['British Airways и United летают прямо', 'Полярный маршрут — короче чем кажется'],
    tips_en: ['British Airways and United fly direct', 'Polar route — shorter than it seems'] },
  { from: 'LHR', to: 'SFO', fromCity_ru: 'Лондон', toCity_ru: 'Сан-Франциско', fromCity_en: 'London', toCity_en: 'San Francisco',
    tips_ru: ['10.5 часов полёта на запад', 'Virgin Atlantic — хороший сервис'],
    tips_en: ['10.5 hour westbound flight', 'Virgin Atlantic — good service'] },
  { from: 'JFK', to: 'BCN', fromCity_ru: 'Нью-Йорк', toCity_ru: 'Барселона', fromCity_en: 'New York', toCity_en: 'Barcelona',
    tips_ru: ['Level и PLAY — бюджетные опции', 'Лето в Барселоне жаркое — цены выше'],
    tips_en: ['Level and PLAY are budget options', 'Barcelona summer is hot — prices higher'] },
  { from: 'BCN', to: 'JFK', fromCity_ru: 'Барселона', toCity_ru: 'Нью-Йорк', fromCity_en: 'Barcelona', toCity_en: 'New York',
    tips_ru: ['Vueling базируется в Барселоне', 'Girona (GRO) — альтернативный аэропорт'],
    tips_en: ['Vueling is based in Barcelona', 'Girona (GRO) is alternative airport'] },
  { from: 'ORD', to: 'MUC', fromCity_ru: 'Чикаго', toCity_ru: 'Мюнхен', fromCity_en: 'Chicago', toCity_en: 'Munich',
    tips_ru: ['Lufthansa прямой рейс', 'United из Chicago часто дешевле'],
    tips_en: ['Lufthansa direct flight', 'United from Chicago often cheaper'] },
  { from: 'MUC', to: 'ORD', fromCity_ru: 'Мюнхен', toCity_ru: 'Чикаго', fromCity_en: 'Munich', toCity_en: 'Chicago',
    tips_ru: ['Memmingen (FMM) — бюджетный аэропорт Ryanair', 'Октоберфест — цены взлетают в сентябре'],
    tips_en: ['Memmingen (FMM) — Ryanair budget airport', 'Oktoberfest — prices spike in September'] },
  { from: 'ATL', to: 'CDG', fromCity_ru: 'Атланта', toCity_ru: 'Париж', fromCity_en: 'Atlanta', toCity_en: 'Paris',
    tips_ru: ['Delta прямой рейс из крупнейшего hub', 'Air France партнёр Delta'],
    tips_en: ['Delta direct from largest hub', 'Air France is Delta partner'] },
  { from: 'DFW', to: 'LHR', fromCity_ru: 'Даллас', toCity_ru: 'Лондон', fromCity_en: 'Dallas', toCity_en: 'London',
    tips_ru: ['American Airlines прямой рейс 9 часов', 'British Airways партнёр American'],
    tips_en: ['American Airlines direct 9 hours', 'British Airways partners with American'] },
  { from: 'IAH', to: 'CDG', fromCity_ru: 'Хьюстон', toCity_ru: 'Париж', fromCity_en: 'Houston', toCity_en: 'Paris',
    tips_ru: ['United прямой рейс', 'Air France также летает на маршруте'],
    tips_en: ['United direct flight', 'Air France also flies the route'] },
  { from: 'PHL', to: 'LHR', fromCity_ru: 'Филадельфия', toCity_ru: 'Лондон', fromCity_en: 'Philadelphia', toCity_en: 'London',
    tips_ru: ['American Airlines hub в Филадельфии', 'Дешевле чем из JFK на 10-15%'],
    tips_en: ['American Airlines hub in Philadelphia', '10-15% cheaper than from JFK'] },

  // ===== US ↔ ASIA (20 routes) =====
  { from: 'LAX', to: 'NRT', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Токио', fromCity_en: 'Los Angeles', toCity_en: 'Tokyo',
    tips_ru: ['Зимой (кроме праздников) — самые низкие цены', 'ANA и JAL часто дешевле из LAX', 'Haneda (HND) ближе к центру'],
    tips_en: ['Winter (except holidays) has lowest prices', 'ANA and JAL often cheapest from LAX', 'Haneda (HND) closer to downtown'] },
  { from: 'NRT', to: 'LAX', fromCity_ru: 'Токио', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Tokyo', toCity_en: 'Los Angeles',
    tips_ru: ['11 часов прямого перелёта', 'Вылет вечером — прибытие утром того же дня'],
    tips_en: ['11 hour direct flight', 'Evening departure — morning arrival same day'] },
  { from: 'SFO', to: 'ICN', fromCity_ru: 'Сан-Франциско', toCity_ru: 'Сеул', fromCity_en: 'San Francisco', toCity_en: 'Seoul',
    tips_ru: ['Korean Air и Asiana — отличный сервис', 'United также летает прямо'],
    tips_en: ['Korean Air and Asiana — excellent service', 'United also flies direct'] },
  { from: 'ICN', to: 'SFO', fromCity_ru: 'Сеул', toCity_ru: 'Сан-Франциско', fromCity_en: 'Seoul', toCity_en: 'San Francisco',
    tips_ru: ['Incheon — один из лучших аэропортов мира', 'Вылет ночью — прибытие вечером предыдущего дня'],
    tips_en: ['Incheon is one of world\'s best airports', 'Night departure — evening arrival previous day'] },
  { from: 'JFK', to: 'BKK', fromCity_ru: 'Нью-Йорк', toCity_ru: 'Бангкок', fromCity_en: 'New York', toCity_en: 'Bangkok',
    tips_ru: ['Только с пересадкой — обычно через Азию', 'Eva Air через Тайбэй — отличный вариант'],
    tips_en: ['Connections only — usually via Asia', 'Eva Air via Taipei is great option'] },
  { from: 'BKK', to: 'JFK', fromCity_ru: 'Бангкок', toCity_ru: 'Нью-Йорк', fromCity_en: 'Bangkok', toCity_en: 'New York',
    tips_ru: ['Через Катар или Эмираты — удобные варианты', 'Thai Airways партнёр Star Alliance'],
    tips_en: ['Via Qatar or Emirates — convenient options', 'Thai Airways is Star Alliance partner'] },
  { from: 'LAX', to: 'HKG', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Гонконг', fromCity_en: 'Los Angeles', toCity_en: 'Hong Kong',
    tips_ru: ['Cathay Pacific — премиум перевозчик', 'United и American также летают прямо'],
    tips_en: ['Cathay Pacific is premium carrier', 'United and American also fly direct'] },
  { from: 'HKG', to: 'LAX', fromCity_ru: 'Гонконг', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Hong Kong', toCity_en: 'Los Angeles',
    tips_ru: ['15 часов над Тихим океаном', 'Вылет днём — прибытие утром'],
    tips_en: ['15 hours over Pacific', 'Day departure — morning arrival'] },
  { from: 'SFO', to: 'PVG', fromCity_ru: 'Сан-Франциско', toCity_ru: 'Шанхай', fromCity_en: 'San Francisco', toCity_en: 'Shanghai',
    tips_ru: ['United прямой рейс 12 часов', 'China Eastern также летает'],
    tips_en: ['United direct flight 12 hours', 'China Eastern also flies'] },
  { from: 'PVG', to: 'SFO', fromCity_ru: 'Шанхай', toCity_ru: 'Сан-Франциско', fromCity_en: 'Shanghai', toCity_en: 'San Francisco',
    tips_ru: ['Pudong Airport современный и удобный', 'Вылет вечером удобнее утреннего'],
    tips_en: ['Pudong Airport modern and convenient', 'Evening departure more convenient than morning'] },
  { from: 'LAX', to: 'SIN', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Сингапур', fromCity_en: 'Los Angeles', toCity_en: 'Singapore',
    tips_ru: ['Singapore Airlines — лучший сервис', 'Changi Airport — лучший в мире'],
    tips_en: ['Singapore Airlines — best service', 'Changi Airport is world\'s best'] },
  { from: 'SIN', to: 'LAX', fromCity_ru: 'Сингапур', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Singapore', toCity_en: 'Los Angeles',
    tips_ru: ['17 часов прямого перелёта', 'Через Токио или Сеул бывает дешевле'],
    tips_en: ['17 hour nonstop flight', 'Via Tokyo or Seoul can be cheaper'] },
  { from: 'ORD', to: 'NRT', fromCity_ru: 'Чикаго', toCity_ru: 'Токио', fromCity_en: 'Chicago', toCity_en: 'Tokyo',
    tips_ru: ['United и ANA летают прямо', '13 часов над полюсом'],
    tips_en: ['United and ANA fly direct', '13 hours over the pole'] },
  { from: 'JFK', to: 'DEL', fromCity_ru: 'Нью-Йорк', toCity_ru: 'Дели', fromCity_en: 'New York', toCity_en: 'Delhi',
    tips_ru: ['Air India прямой рейс 14 часов', 'Через Европу часто дешевле'],
    tips_en: ['Air India direct 14 hours', 'Via Europe often cheaper'] },
  { from: 'DEL', to: 'JFK', fromCity_ru: 'Дели', toCity_ru: 'Нью-Йорк', fromCity_en: 'Delhi', toCity_en: 'New York',
    tips_ru: ['Indira Gandhi Airport большой и загруженный', 'Вылет ночью — прибытие утром'],
    tips_en: ['Indira Gandhi Airport large and busy', 'Night departure — morning arrival'] },
  { from: 'SFO', to: 'BOM', fromCity_ru: 'Сан-Франциско', toCity_ru: 'Мумбаи', fromCity_en: 'San Francisco', toCity_en: 'Mumbai',
    tips_ru: ['Air India прямой рейс', 'United через Дели также хороший вариант'],
    tips_en: ['Air India direct flight', 'United via Delhi also good option'] },
  { from: 'LAX', to: 'MNL', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Манила', fromCity_en: 'Los Angeles', toCity_en: 'Manila',
    tips_ru: ['Philippine Airlines прямой рейс', 'Через Токио или Сеул дешевле'],
    tips_en: ['Philippine Airlines direct', 'Via Tokyo or Seoul is cheaper'] },
  { from: 'SFO', to: 'HND', fromCity_ru: 'Сан-Франциско', toCity_ru: 'Токио-Ханеда', fromCity_en: 'San Francisco', toCity_en: 'Tokyo Haneda',
    tips_ru: ['Haneda ближе к центру чем Narita', 'United и ANA летают прямо'],
    tips_en: ['Haneda closer to downtown than Narita', 'United and ANA fly direct'] },
  { from: 'SEA', to: 'ICN', fromCity_ru: 'Сиэтл', toCity_ru: 'Сеул', fromCity_en: 'Seattle', toCity_en: 'Seoul',
    tips_ru: ['Korean Air и Delta летают прямо', 'Полярный маршрут — короче обычного'],
    tips_en: ['Korean Air and Delta fly direct', 'Polar route — shorter than usual'] },
  { from: 'LAX', to: 'TPE', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Тайбэй', fromCity_en: 'Los Angeles', toCity_en: 'Taipei',
    tips_ru: ['Eva Air и China Airlines летают прямо', 'Taoyuan Airport удобный для пересадок'],
    tips_en: ['Eva Air and China Airlines fly direct', 'Taoyuan Airport convenient for connections'] },

  // ===== US ↔ LATIN AMERICA (18 routes) =====
  { from: 'LAX', to: 'CUN', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Канкун', fromCity_en: 'Los Angeles', toCity_en: 'Cancun',
    tips_ru: ['Прямые рейсы от $200 в несезон', 'Volaris и VivaAerobus — лоукостеры', 'Май-октябрь — дождливый сезон, дешевле'],
    tips_en: ['Direct flights from $200 off-season', 'Volaris and VivaAerobus are budget carriers', 'May-October rainy season, cheaper'] },
  { from: 'CUN', to: 'LAX', fromCity_ru: 'Канкун', toCity_ru: 'Лос-Анджелес', fromCity_en: 'Cancun', toCity_en: 'Los Angeles',
    tips_ru: ['4.5 часа прямого перелёта', 'Воскресенье — самый дорогой день вылета'],
    tips_en: ['4.5 hour direct flight', 'Sunday is most expensive departure day'] },
  { from: 'MIA', to: 'BOG', fromCity_ru: 'Майами', toCity_ru: 'Богота', fromCity_en: 'Miami', toCity_en: 'Bogota',
    tips_ru: ['Spirit Airlines — самые дешёвые билеты', 'Avianca — лучший сервис', 'Богота на высоте 2600м — учитывай акклиматизацию'],
    tips_en: ['Spirit Airlines — cheapest tickets', 'Avianca — best service', 'Bogota at 2600m altitude — consider acclimatization'] },
  { from: 'BOG', to: 'MIA', fromCity_ru: 'Богота', toCity_ru: 'Майами', fromCity_en: 'Bogota', toCity_en: 'Miami',
    tips_ru: ['Прямой рейс 3.5 часа', 'Copa через Панаму также удобный вариант'],
    tips_en: ['Direct flight 3.5 hours', 'Copa via Panama also convenient'] },
  { from: 'JFK', to: 'MEX', fromCity_ru: 'Нью-Йорк', toCity_ru: 'Мехико', fromCity_en: 'New York', toCity_en: 'Mexico City',
    tips_ru: ['Aeromexico и Delta партнёры', 'Высота 2250м — возможна горная болезнь'],
    tips_en: ['Aeromexico and Delta are partners', 'Altitude 2250m — altitude sickness possible'] },
  { from: 'MEX', to: 'JFK', fromCity_ru: 'Мехико', toCity_ru: 'Нью-Йорк', fromCity_en: 'Mexico City', toCity_en: 'New York',
    tips_ru: ['5 часов прямого перелёта', 'Toluca (TLC) — бюджетная альтернатива'],
    tips_en: ['5 hour direct flight', 'Toluca (TLC) is budget alternative'] },
  { from: 'LAX', to: 'GDL', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Гвадалахара', fromCity_en: 'Los Angeles', toCity_en: 'Guadalajara',
    tips_ru: ['Volaris часто дешевле всех', 'Прямой рейс 3 часа'],
    tips_en: ['Volaris often cheapest', 'Direct flight 3 hours'] },
  { from: 'MIA', to: 'LIM', fromCity_ru: 'Майами', toCity_ru: 'Лима', fromCity_en: 'Miami', toCity_en: 'Lima',
    tips_ru: ['LATAM базируется в Лиме', 'Зимой в Перу (июнь-август) — высокий сезон'],
    tips_en: ['LATAM is based in Lima', 'Peruvian winter (June-Aug) is high season'] },
  { from: 'LIM', to: 'MIA', fromCity_ru: 'Лима', toCity_ru: 'Майами', fromCity_en: 'Lima', toCity_en: 'Miami',
    tips_ru: ['6 часов прямого перелёта', 'Copa через Панаму часто дешевле'],
    tips_en: ['6 hour direct flight', 'Copa via Panama often cheaper'] },
  { from: 'DFW', to: 'CUN', fromCity_ru: 'Даллас', toCity_ru: 'Канкун', fromCity_en: 'Dallas', toCity_en: 'Cancun',
    tips_ru: ['American Airlines много рейсов', '2.5 часа короткого перелёта'],
    tips_en: ['American Airlines many flights', '2.5 hour short flight'] },
  { from: 'LAX', to: 'PTY', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Панама', fromCity_en: 'Los Angeles', toCity_en: 'Panama City',
    tips_ru: ['Copa Airlines hub в Панаме', 'Удобно для пересадок по Южной Америке'],
    tips_en: ['Copa Airlines hub in Panama', 'Convenient for South America connections'] },
  { from: 'MIA', to: 'GRU', fromCity_ru: 'Майами', toCity_ru: 'Сан-Паулу', fromCity_en: 'Miami', toCity_en: 'Sao Paulo',
    tips_ru: ['American и LATAM летают прямо', 'Congonhas (CGH) удобнее чем Guarulhos'],
    tips_en: ['American and LATAM fly direct', 'Congonhas (CGH) more convenient than Guarulhos'] },
  { from: 'JFK', to: 'GIG', fromCity_ru: 'Нью-Йорк', toCity_ru: 'Рио-де-Жанейро', fromCity_en: 'New York', toCity_en: 'Rio de Janeiro',
    tips_ru: ['Ночной рейс 9.5 часов — прибытие утром', 'Февраль — карнавал, цены взлетают'],
    tips_en: ['Night flight 9.5 hours — morning arrival', 'February carnival — prices skyrocket'] },
  { from: 'IAH', to: 'CUN', fromCity_ru: 'Хьюстон', toCity_ru: 'Канкун', fromCity_en: 'Houston', toCity_en: 'Cancun',
    tips_ru: ['United прямой рейс 2 часа', 'Spirit дешевле но без багажа'],
    tips_en: ['United direct 2 hours', 'Spirit cheaper but no bags'] },
  { from: 'ATL', to: 'CUN', fromCity_ru: 'Атланта', toCity_ru: 'Канкун', fromCity_en: 'Atlanta', toCity_en: 'Cancun',
    tips_ru: ['Delta много рейсов из крупнейшего hub', 'Прямой рейс 2.5 часа'],
    tips_en: ['Delta many flights from largest hub', 'Direct flight 2.5 hours'] },
  { from: 'ORD', to: 'CUN', fromCity_ru: 'Чикаго', toCity_ru: 'Канкун', fromCity_en: 'Chicago', toCity_en: 'Cancun',
    tips_ru: ['United и Volaris летают прямо', 'Зима — побег от холода Чикаго'],
    tips_en: ['United and Volaris fly direct', 'Winter — escape from Chicago cold'] },
  { from: 'MIA', to: 'CCS', fromCity_ru: 'Майами', toCity_ru: 'Каракас', fromCity_en: 'Miami', toCity_en: 'Caracas',
    tips_ru: ['Ограниченное количество рейсов', 'Проверяй визовые требования'],
    tips_en: ['Limited flight availability', 'Check visa requirements'] },
  { from: 'LAX', to: 'SJO', fromCity_ru: 'Лос-Анджелес', toCity_ru: 'Сан-Хосе', fromCity_en: 'Los Angeles', toCity_en: 'San Jose CR',
    tips_ru: ['Alaska Airlines хорошие цены', 'Коста-Рика — виза не нужна'],
    tips_en: ['Alaska Airlines good prices', 'Costa Rica — no visa needed'] },

  // ===== RUSSIA/CIS (35 routes) =====
  { from: 'SVO', to: 'LED', fromCity_ru: 'Москва', toCity_ru: 'Санкт-Петербург', fromCity_en: 'Moscow', toCity_en: 'Saint Petersburg',
    tips_ru: ['Самый популярный маршрут в России', 'Победа и S7 — самые дешёвые', 'Час полёта — быстрее поезда'],
    tips_en: ['Most popular route in Russia', 'Pobeda and S7 are cheapest', 'One hour flight — faster than train'] },
  { from: 'LED', to: 'SVO', fromCity_ru: 'Санкт-Петербург', toCity_ru: 'Москва', fromCity_en: 'Saint Petersburg', toCity_en: 'Moscow',
    tips_ru: ['Каждые 30 минут есть рейс', 'Pulkovo удобный компактный аэропорт'],
    tips_en: ['Flight every 30 minutes', 'Pulkovo is convenient compact airport'] },
  { from: 'SVO', to: 'IST', fromCity_ru: 'Москва', toCity_ru: 'Стамбул', fromCity_en: 'Moscow', toCity_en: 'Istanbul',
    tips_ru: ['Turkish Airlines — лучший сервис', 'Pegasus — бюджетный вариант', 'Sabiha Gokcen (SAW) дешевле чем IST'],
    tips_en: ['Turkish Airlines — best service', 'Pegasus — budget option', 'Sabiha Gokcen (SAW) cheaper than IST'] },
  { from: 'IST', to: 'SVO', fromCity_ru: 'Стамбул', toCity_ru: 'Москва', fromCity_en: 'Istanbul', toCity_en: 'Moscow',
    tips_ru: ['3 часа прямого перелёта', 'Новый аэропорт IST огромный — приезжай заранее'],
    tips_en: ['3 hour direct flight', 'New IST airport is huge — arrive early'] },
  { from: 'SVO', to: 'DXB', fromCity_ru: 'Москва', toCity_ru: 'Дубай', fromCity_en: 'Moscow', toCity_en: 'Dubai',
    tips_ru: ['Лето — самые низкие цены (жара)', 'FlyDubai дешевле Emirates', 'Без визы до 90 дней'],
    tips_en: ['Summer has lowest prices (heat)', 'FlyDubai cheaper than Emirates', 'Visa-free up to 90 days'] },
  { from: 'DXB', to: 'SVO', fromCity_ru: 'Дубай', toCity_ru: 'Москва', fromCity_en: 'Dubai', toCity_en: 'Moscow',
    tips_ru: ['5 часов прямого перелёта', 'Emirates — люксовый перевозчик'],
    tips_en: ['5 hour direct flight', 'Emirates is luxury carrier'] },
  { from: 'SVO', to: 'AYT', fromCity_ru: 'Москва', toCity_ru: 'Анталья', fromCity_en: 'Moscow', toCity_en: 'Antalya',
    tips_ru: ['Чартеры часто дешевле регулярных рейсов', 'Бронируй за 1-2 месяца', 'Май-октябрь — сезон'],
    tips_en: ['Charters often cheaper than scheduled flights', 'Book 1-2 months ahead', 'May-October is season'] },
  { from: 'AYT', to: 'SVO', fromCity_ru: 'Анталья', toCity_ru: 'Москва', fromCity_en: 'Antalya', toCity_en: 'Moscow',
    tips_ru: ['3 часа полёта домой', 'Не забудь купить турецкий чай в аэропорту'],
    tips_en: ['3 hour flight home', 'Don\'t forget Turkish tea at airport'] },
  { from: 'SVO', to: 'TBS', fromCity_ru: 'Москва', toCity_ru: 'Тбилиси', fromCity_en: 'Moscow', toCity_en: 'Tbilisi',
    tips_ru: ['Много лоукостеров на маршруте', 'Без визы для россиян', 'Red Wings и Azimuth часто дешёвые'],
    tips_en: ['Many budget carriers on route', 'Visa-free for Russians', 'Red Wings and Azimuth often cheap'] },
  { from: 'TBS', to: 'SVO', fromCity_ru: 'Тбилиси', toCity_ru: 'Москва', fromCity_en: 'Tbilisi', toCity_en: 'Moscow',
    tips_ru: ['2.5 часа полёта', 'Georgian Airways — национальный перевозчик'],
    tips_en: ['2.5 hour flight', 'Georgian Airways is national carrier'] },
  { from: 'LED', to: 'IST', fromCity_ru: 'Санкт-Петербург', toCity_ru: 'Стамбул', fromCity_en: 'Saint Petersburg', toCity_en: 'Istanbul',
    tips_ru: ['Turkish Airlines прямой рейс', 'Pegasus дешевле но через Sabiha'],
    tips_en: ['Turkish Airlines direct', 'Pegasus cheaper but via Sabiha'] },
  { from: 'IST', to: 'LED', fromCity_ru: 'Стамбул', toCity_ru: 'Санкт-Петербург', fromCity_en: 'Istanbul', toCity_en: 'Saint Petersburg',
    tips_ru: ['3.5 часа прямого перелёта', 'Белые ночи в июне — дорого'],
    tips_en: ['3.5 hour direct flight', 'White nights in June — expensive'] },
  { from: 'SVO', to: 'EVN', fromCity_ru: 'Москва', toCity_ru: 'Ереван', fromCity_en: 'Moscow', toCity_en: 'Yerevan',
    tips_ru: ['Много рейсов — Армения близко', 'Без визы для россиян'],
    tips_en: ['Many flights — Armenia is close', 'Visa-free for Russians'] },
  { from: 'EVN', to: 'SVO', fromCity_ru: 'Ереван', toCity_ru: 'Москва', fromCity_en: 'Yerevan', toCity_en: 'Moscow',
    tips_ru: ['2.5 часа полёта', 'Zvartnots новый удобный аэропорт'],
    tips_en: ['2.5 hour flight', 'Zvartnots is new convenient airport'] },
  { from: 'SVO', to: 'AER', fromCity_ru: 'Москва', toCity_ru: 'Сочи', fromCity_en: 'Moscow', toCity_en: 'Sochi',
    tips_ru: ['Курорт круглый год', 'Лето — пляж, зима — горы'],
    tips_en: ['Year-round resort', 'Summer — beach, winter — mountains'] },
  { from: 'AER', to: 'SVO', fromCity_ru: 'Сочи', toCity_ru: 'Москва', fromCity_en: 'Sochi', toCity_en: 'Moscow',
    tips_ru: ['2 часа полёта домой', 'Adler аэропорт современный после Олимпиады'],
    tips_en: ['2 hour flight home', 'Adler airport modern after Olympics'] },
  { from: 'SVO', to: 'KZN', fromCity_ru: 'Москва', toCity_ru: 'Казань', fromCity_en: 'Moscow', toCity_en: 'Kazan',
    tips_ru: ['Час полёта — очень быстро', 'S7 и Победа дешёвые'],
    tips_en: ['One hour flight — very fast', 'S7 and Pobeda are cheap'] },
  { from: 'KZN', to: 'SVO', fromCity_ru: 'Казань', toCity_ru: 'Москва', fromCity_en: 'Kazan', toCity_en: 'Moscow',
    tips_ru: ['Много рейсов в день', 'Казань красивый город — стоит остаться подольше'],
    tips_en: ['Many daily flights', 'Kazan is beautiful — worth staying longer'] },
  { from: 'SVO', to: 'KRR', fromCity_ru: 'Москва', toCity_ru: 'Краснодар', fromCity_en: 'Moscow', toCity_en: 'Krasnodar',
    tips_ru: ['2 часа полёта на юг', 'Ворота Черного моря'],
    tips_en: ['2 hour flight south', 'Gateway to Black Sea'] },
  { from: 'SVO', to: 'VKO', fromCity_ru: 'Москва-Шереметьево', toCity_ru: 'Москва-Внуково', fromCity_en: 'Moscow SVO', toCity_en: 'Moscow VKO',
    tips_ru: ['Пересадка между аэропортами', 'Аэроэкспресс удобнее такси'],
    tips_en: ['Airport transfer', 'Aeroexpress more convenient than taxi'] },
  { from: 'SVO', to: 'BAK', fromCity_ru: 'Москва', toCity_ru: 'Баку', fromCity_en: 'Moscow', toCity_en: 'Baku',
    tips_ru: ['Azerbaijan Airlines прямой рейс', 'Виза онлайн за 3 дня'],
    tips_en: ['Azerbaijan Airlines direct', 'E-visa in 3 days'] },
  { from: 'BAK', to: 'SVO', fromCity_ru: 'Баку', toCity_ru: 'Москва', fromCity_en: 'Baku', toCity_en: 'Moscow',
    tips_ru: ['3 часа прямого перелёта', 'Heydar Aliyev Airport современный'],
    tips_en: ['3 hour direct flight', 'Heydar Aliyev Airport is modern'] },
  { from: 'SVO', to: 'SVX', fromCity_ru: 'Москва', toCity_ru: 'Екатеринбург', fromCity_en: 'Moscow', toCity_en: 'Yekaterinburg',
    tips_ru: ['2 часа полёта на восток', 'Граница Европа-Азия'],
    tips_en: ['2 hour flight east', 'Europe-Asia border'] },
  { from: 'SVX', to: 'SVO', fromCity_ru: 'Екатеринбург', toCity_ru: 'Москва', fromCity_en: 'Yekaterinburg', toCity_en: 'Moscow',
    tips_ru: ['Разница во времени +2 часа', 'Koltsovo удобный аэропорт'],
    tips_en: ['Time difference +2 hours', 'Koltsovo is convenient airport'] },
  { from: 'SVO', to: 'OVB', fromCity_ru: 'Москва', toCity_ru: 'Новосибирск', fromCity_en: 'Moscow', toCity_en: 'Novosibirsk',
    tips_ru: ['4 часа полёта в Сибирь', 'S7 базируется в Новосибирске'],
    tips_en: ['4 hour flight to Siberia', 'S7 is based in Novosibirsk'] },
  { from: 'OVB', to: 'SVO', fromCity_ru: 'Новосибирск', toCity_ru: 'Москва', fromCity_en: 'Novosibirsk', toCity_en: 'Moscow',
    tips_ru: ['Разница +4 часа — джетлаг', 'Tolmachevo крупнейший аэропорт Сибири'],
    tips_en: ['Time difference +4 hours — jet lag', 'Tolmachevo is largest Siberian airport'] },
  { from: 'SVO', to: 'ALA', fromCity_ru: 'Москва', toCity_ru: 'Алматы', fromCity_en: 'Moscow', toCity_en: 'Almaty',
    tips_ru: ['4 часа полёта в Казахстан', 'Air Astana отличный сервис'],
    tips_en: ['4 hour flight to Kazakhstan', 'Air Astana excellent service'] },
  { from: 'ALA', to: 'SVO', fromCity_ru: 'Алматы', toCity_ru: 'Москва', fromCity_en: 'Almaty', toCity_en: 'Moscow',
    tips_ru: ['Без визы для россиян', 'Горы красивые — стоит задержаться'],
    tips_en: ['Visa-free for Russians', 'Mountains beautiful — worth staying'] },
  { from: 'SVO', to: 'TAS', fromCity_ru: 'Москва', toCity_ru: 'Ташкент', fromCity_en: 'Moscow', toCity_en: 'Tashkent',
    tips_ru: ['4 часа полёта в Узбекистан', 'Uzbekistan Airways национальный перевозчик'],
    tips_en: ['4 hour flight to Uzbekistan', 'Uzbekistan Airways is national carrier'] },
  { from: 'TAS', to: 'SVO', fromCity_ru: 'Ташкент', toCity_ru: 'Москва', fromCity_en: 'Tashkent', toCity_en: 'Moscow',
    tips_ru: ['Без визы 60 дней', 'Новый терминал очень современный'],
    tips_en: ['Visa-free 60 days', 'New terminal very modern'] },
  { from: 'SVO', to: 'GYD', fromCity_ru: 'Москва', toCity_ru: 'Баку', fromCity_en: 'Moscow', toCity_en: 'Baku',
    tips_ru: ['То же что BAK — оба кода Баку', 'AZAL часто проводит распродажи'],
    tips_en: ['Same as BAK — both are Baku codes', 'AZAL often has sales'] },
  { from: 'SVO', to: 'MRV', fromCity_ru: 'Москва', toCity_ru: 'Минеральные Воды', fromCity_en: 'Moscow', toCity_en: 'Mineralnye Vody',
    tips_ru: ['2 часа полёта на Кавказ', 'Ворота к курортам КМВ'],
    tips_en: ['2 hour flight to Caucasus', 'Gateway to KMV resorts'] },
  { from: 'MRV', to: 'SVO', fromCity_ru: 'Минеральные Воды', toCity_ru: 'Москва', fromCity_en: 'Mineralnye Vody', toCity_en: 'Moscow',
    tips_ru: ['Пятигорск и Ессентуки близко', 'Небольшой аэропорт — быстрая регистрация'],
    tips_en: ['Pyatigorsk and Essentuki nearby', 'Small airport — fast check-in'] },
  { from: 'LED', to: 'TBS', fromCity_ru: 'Санкт-Петербург', toCity_ru: 'Тбилиси', fromCity_en: 'Saint Petersburg', toCity_en: 'Tbilisi',
    tips_ru: ['Прямые рейсы несколько раз в неделю', 'Belavia через Минск дешевле'],
    tips_en: ['Direct flights several times a week', 'Belavia via Minsk is cheaper'] },
  { from: 'SVO', to: 'KGD', fromCity_ru: 'Москва', toCity_ru: 'Калининград', fromCity_en: 'Moscow', toCity_en: 'Kaliningrad',
    tips_ru: ['2 часа полёта над Прибалтикой', 'Без паспорта не пустят — эксклав'],
    tips_en: ['2 hour flight over Baltics', 'Need passport — it\'s an exclave'] },
  { from: 'KGD', to: 'SVO', fromCity_ru: 'Калининград', toCity_ru: 'Москва', fromCity_en: 'Kaliningrad', toCity_en: 'Moscow',
    tips_ru: ['Khrabrovo небольой уютный аэропорт', 'Янтарь не забудь купить'],
    tips_en: ['Khrabrovo is small cozy airport', 'Don\'t forget to buy amber'] },

  // ===== EUROPE INTERNAL (25 routes) =====
  { from: 'LHR', to: 'CDG', fromCity_ru: 'Лондон', toCity_ru: 'Париж', fromCity_en: 'London', toCity_en: 'Paris',
    tips_ru: ['Eurostar поезд быстрее самолёта', 'Ryanair из Stansted дешевле', 'City Airport (LCY) ближе к центру'],
    tips_en: ['Eurostar train faster than plane', 'Ryanair from Stansted cheaper', 'City Airport (LCY) closer to downtown'] },
  { from: 'CDG', to: 'LHR', fromCity_ru: 'Париж', toCity_ru: 'Лондон', fromCity_en: 'Paris', toCity_en: 'London',
    tips_ru: ['Час полёта но 3 часа в аэропортах', 'EasyJet хороший бюджетный вариант'],
    tips_en: ['One hour flight but 3 hours at airports', 'EasyJet good budget option'] },
  { from: 'BCN', to: 'FCO', fromCity_ru: 'Барселона', toCity_ru: 'Рим', fromCity_en: 'Barcelona', toCity_en: 'Rome',
    tips_ru: ['Ryanair и Vueling летают часто', '2 часа перелёта — удобно для выходных'],
    tips_en: ['Ryanair and Vueling fly frequently', '2 hour flight — convenient for weekends'] },
  { from: 'FCO', to: 'BCN', fromCity_ru: 'Рим', toCity_ru: 'Барселона', fromCity_en: 'Rome', toCity_en: 'Barcelona',
    tips_ru: ['ITA Airways и Vueling конкурируют', 'Лето — высокий сезон в обоих городах'],
    tips_en: ['ITA Airways and Vueling compete', 'Summer is high season in both cities'] },
  { from: 'AMS', to: 'BER', fromCity_ru: 'Амстердам', toCity_ru: 'Берлин', fromCity_en: 'Amsterdam', toCity_en: 'Berlin',
    tips_ru: ['Час полёта — быстро', 'KLM и Lufthansa основные перевозчики'],
    tips_en: ['One hour flight — quick', 'KLM and Lufthansa are main carriers'] },
  { from: 'BER', to: 'AMS', fromCity_ru: 'Берлин', toCity_ru: 'Амстердам', fromCity_en: 'Berlin', toCity_en: 'Amsterdam',
    tips_ru: ['Новый аэропорт BER заменил Tegel', 'EasyJet дешевле флагманов'],
    tips_en: ['New BER airport replaced Tegel', 'EasyJet cheaper than flagships'] },
  { from: 'LHR', to: 'MAD', fromCity_ru: 'Лондон', toCity_ru: 'Мадрид', fromCity_en: 'London', toCity_en: 'Madrid',
    tips_ru: ['2.5 часа полёта', 'British Airways и Iberia партнёры'],
    tips_en: ['2.5 hour flight', 'British Airways and Iberia are partners'] },
  { from: 'MAD', to: 'LHR', fromCity_ru: 'Мадрид', toCity_ru: 'Лондон', fromCity_en: 'Madrid', toCity_en: 'London',
    tips_ru: ['Ryanair летает в Stansted', 'Barajas T4 огромный — приезжай заранее'],
    tips_en: ['Ryanair flies to Stansted', 'Barajas T4 is huge — arrive early'] },
  { from: 'MUC', to: 'VIE', fromCity_ru: 'Мюнхен', toCity_ru: 'Вена', fromCity_en: 'Munich', toCity_en: 'Vienna',
    tips_ru: ['Час полёта между столицами', 'Austrian и Lufthansa летают часто'],
    tips_en: ['One hour flight between capitals', 'Austrian and Lufthansa fly frequently'] },
  { from: 'VIE', to: 'MUC', fromCity_ru: 'Вена', toCity_ru: 'Мюнхен', fromCity_en: 'Vienna', toCity_en: 'Munich',
    tips_ru: ['Можно на поезде за 4 часа', 'Schwechat удобный компактный аэропорт'],
    tips_en: ['Can take train in 4 hours', 'Schwechat is convenient compact airport'] },
  { from: 'CDG', to: 'BCN', fromCity_ru: 'Париж', toCity_ru: 'Барселона', fromCity_en: 'Paris', toCity_en: 'Barcelona',
    tips_ru: ['2 часа полёта на юг', 'Vueling и Air France конкурируют'],
    tips_en: ['2 hour flight south', 'Vueling and Air France compete'] },
  { from: 'BCN', to: 'CDG', fromCity_ru: 'Барселона', toCity_ru: 'Париж', fromCity_en: 'Barcelona', toCity_en: 'Paris',
    tips_ru: ['Orly (ORY) ближе к центру Парижа', 'EasyJet часто дешевле всех'],
    tips_en: ['Orly (ORY) closer to Paris center', 'EasyJet often cheapest'] },
  { from: 'LIS', to: 'MAD', fromCity_ru: 'Лиссабон', toCity_ru: 'Мадрид', fromCity_en: 'Lisbon', toCity_en: 'Madrid',
    tips_ru: ['Час полёта между столицами', 'TAP Portugal и Iberia летают'],
    tips_en: ['One hour flight between capitals', 'TAP Portugal and Iberia fly'] },
  { from: 'MAD', to: 'LIS', fromCity_ru: 'Мадрид', toCity_ru: 'Лиссабон', fromCity_en: 'Madrid', toCity_en: 'Lisbon',
    tips_ru: ['Ryanair очень дешёвый', 'Portela аэропорт близко к центру'],
    tips_en: ['Ryanair very cheap', 'Portela airport close to center'] },
  { from: 'FRA', to: 'ZRH', fromCity_ru: 'Франкфурт', toCity_ru: 'Цюрих', fromCity_en: 'Frankfurt', toCity_en: 'Zurich',
    tips_ru: ['Час полёта — короткий', 'Lufthansa и Swiss летают часто'],
    tips_en: ['One hour flight — short', 'Lufthansa and Swiss fly frequently'] },
  { from: 'ZRH', to: 'FRA', fromCity_ru: 'Цюрих', toCity_ru: 'Франкфурт', fromCity_en: 'Zurich', toCity_en: 'Frankfurt',
    tips_ru: ['Швейцария дорогая — всё дороже', 'Kloten аэропорт маленький удобный'],
    tips_en: ['Switzerland expensive — everything costs more', 'Kloten airport small and convenient'] },
  { from: 'CPH', to: 'ARN', fromCity_ru: 'Копенгаген', toCity_ru: 'Стокгольм', fromCity_en: 'Copenhagen', toCity_en: 'Stockholm',
    tips_ru: ['Час полёта между скандинавскими столицами', 'SAS основной перевозчик'],
    tips_en: ['One hour flight between Scandinavian capitals', 'SAS is main carrier'] },
  { from: 'ARN', to: 'CPH', fromCity_ru: 'Стокгольм', toCity_ru: 'Копенгаген', fromCity_en: 'Stockholm', toCity_en: 'Copenhagen',
    tips_ru: ['Norwegian дешевле SAS', 'Arlanda далеко от центра — планируй трансфер'],
    tips_en: ['Norwegian cheaper than SAS', 'Arlanda far from center — plan transfer'] },
  { from: 'OSL', to: 'CPH', fromCity_ru: 'Осло', toCity_ru: 'Копенгаген', fromCity_en: 'Oslo', toCity_en: 'Copenhagen',
    tips_ru: ['Час полёта — удобно', 'Норвегия дорогая как Швейцария'],
    tips_en: ['One hour flight — convenient', 'Norway expensive like Switzerland'] },
  { from: 'DUB', to: 'LHR', fromCity_ru: 'Дублин', toCity_ru: 'Лондон', fromCity_en: 'Dublin', toCity_en: 'London',
    tips_ru: ['Час полёта через Ирландское море', 'Ryanair из Дублина супердёшево'],
    tips_en: ['One hour flight across Irish Sea', 'Ryanair from Dublin super cheap'] },
  { from: 'LHR', to: 'DUB', fromCity_ru: 'Лондон', toCity_ru: 'Дублин', fromCity_en: 'London', toCity_en: 'Dublin',
    tips_ru: ['Aer Lingus ирландский флагман', 'City Airport удобен для деловых поездок'],
    tips_en: ['Aer Lingus is Irish flagship', 'City Airport convenient for business'] },
  { from: 'ATH', to: 'FCO', fromCity_ru: 'Афины', toCity_ru: 'Рим', fromCity_en: 'Athens', toCity_en: 'Rome',
    tips_ru: ['2 часа полёта между древними столицами', 'Aegean Airlines греческий лидер'],
    tips_en: ['2 hour flight between ancient capitals', 'Aegean Airlines is Greek leader'] },
  { from: 'FCO', to: 'ATH', fromCity_ru: 'Рим', toCity_ru: 'Афины', fromCity_en: 'Rome', toCity_en: 'Athens',
    tips_ru: ['Лето — высокий сезон в Греции', 'Ryanair летает в провинцию дешевле'],
    tips_en: ['Summer is high season in Greece', 'Ryanair flies to provinces cheaper'] },
  { from: 'PRG', to: 'VIE', fromCity_ru: 'Прага', toCity_ru: 'Вена', fromCity_en: 'Prague', toCity_en: 'Vienna',
    tips_ru: ['Час полёта — очень близко', 'Можно на автобусе за €15'],
    tips_en: ['One hour flight — very close', 'Can take bus for €15'] },
  { from: 'VIE', to: 'PRG', fromCity_ru: 'Вена', toCity_ru: 'Прага', fromCity_en: 'Vienna', toCity_en: 'Prague',
    tips_ru: ['Austrian Airlines и Czech Airlines партнёры', 'Прага дешевле Вены — тариф на такси'],
    tips_en: ['Austrian Airlines and Czech Airlines partners', 'Prague cheaper than Vienna — taxi fare'] },
  { from: 'BRU', to: 'AMS', fromCity_ru: 'Брюссель', toCity_ru: 'Амстердам', fromCity_en: 'Brussels', toCity_en: 'Amsterdam',
    tips_ru: ['30 минут полёта — самый короткий', 'Поезд Thalys удобнее самолёта'],
    tips_en: ['30 minute flight — shortest', 'Thalys train more convenient than plane'] },

  // ===== ASIA POPULAR (20 routes) =====
  { from: 'NRT', to: 'BKK', fromCity_ru: 'Токио', toCity_ru: 'Бангкок', fromCity_en: 'Tokyo', toCity_en: 'Bangkok',
    tips_ru: ['6 часов полёта на юг', 'ANA и Thai Airways летают прямо', 'Don Mueang (DMK) дешевле Suvarnabhumi'],
    tips_en: ['6 hour flight south', 'ANA and Thai Airways fly direct', 'Don Mueang (DMK) cheaper than Suvarnabhumi'] },
  { from: 'BKK', to: 'NRT', fromCity_ru: 'Бангкок', toCity_ru: 'Токио', fromCity_en: 'Bangkok', toCity_en: 'Tokyo',
    tips_ru: ['JAL и Thai Airways конкурируют', 'Вылет ночью — прибытие утром'],
    tips_en: ['JAL and Thai Airways compete', 'Night departure — morning arrival'] },
  { from: 'SIN', to: 'KUL', fromCity_ru: 'Сингапур', toCity_ru: 'Куала-Лумпур', fromCity_en: 'Singapore', toCity_en: 'Kuala Lumpur',
    tips_ru: ['Час полёта — супер короткий', 'AirAsia очень дешёвый', 'Можно на автобусе за $15'],
    tips_en: ['One hour flight — super short', 'AirAsia very cheap', 'Can take bus for $15'] },
  { from: 'KUL', to: 'SIN', fromCity_ru: 'Куала-Лумпур', toCity_ru: 'Сингапур', fromCity_en: 'Kuala Lumpur', toCity_en: 'Singapore',
    tips_ru: ['KLIA2 для бюджетных авиакомпаний', 'Malaysia Airlines флагман'],
    tips_en: ['KLIA2 for budget airlines', 'Malaysia Airlines is flagship'] },
  { from: 'HKG', to: 'TPE', fromCity_ru: 'Гонконг', toCity_ru: 'Тайбэй', fromCity_en: 'Hong Kong', toCity_en: 'Taipei',
    tips_ru: ['2 часа полёта — близко', 'Cathay Pacific и China Airlines летают'],
    tips_en: ['2 hour flight — close', 'Cathay Pacific and China Airlines fly'] },
  { from: 'TPE', to: 'HKG', fromCity_ru: 'Тайбэй', toCity_ru: 'Гонконг', fromCity_en: 'Taipei', toCity_en: 'Hong Kong',
    tips_ru: ['EVA Air тоже летает', 'Taoyuan современный аэропорт'],
    tips_en: ['EVA Air also flies', 'Taoyuan is modern airport'] },
  { from: 'BKK', to: 'SIN', fromCity_ru: 'Бангкок', toCity_ru: 'Сингапур', fromCity_en: 'Bangkok', toCity_en: 'Singapore',
    tips_ru: ['2.5 часа полёта на юг', 'Scoot бюджетная дочка Singapore Airlines'],
    tips_en: ['2.5 hour flight south', 'Scoot is Singapore Airlines budget subsidiary'] },
  { from: 'SIN', to: 'BKK', fromCity_ru: 'Сингапур', toCity_ru: 'Бангкок', fromCity_en: 'Singapore', toCity_en: 'Bangkok',
    tips_ru: ['Thai Airways и Singapore Airlines конкурируют', 'AirAsia супердёшево'],
    tips_en: ['Thai Airways and Singapore Airlines compete', 'AirAsia super cheap'] },
  { from: 'ICN', to: 'NRT', fromCity_ru: 'Сеул', toCity_ru: 'Токио', fromCity_en: 'Seoul', toCity_en: 'Tokyo',
    tips_ru: ['2 часа полёта — очень удобно', 'Korean Air и JAL часто летают'],
    tips_en: ['2 hour flight — very convenient', 'Korean Air and JAL fly frequently'] },
  { from: 'NRT', to: 'ICN', fromCity_ru: 'Токио', toCity_ru: 'Сеул', fromCity_en: 'Tokyo', toCity_en: 'Seoul',
    tips_ru: ['ANA и Asiana также летают', 'Gimpo (GMP) ближе к центру Сеула'],
    tips_en: ['ANA and Asiana also fly', 'Gimpo (GMP) closer to Seoul center'] },
  { from: 'PEK', to: 'PVG', fromCity_ru: 'Пекин', toCity_ru: 'Шанхай', fromCity_en: 'Beijing', toCity_en: 'Shanghai',
    tips_ru: ['2 часа полёта — внутренний Китай', 'Много рейсов каждый час'],
    tips_en: ['2 hour flight — domestic China', 'Many flights every hour'] },
  { from: 'PVG', to: 'PEK', fromCity_ru: 'Шанхай', toCity_ru: 'Пекин', fromCity_en: 'Shanghai', toCity_en: 'Beijing',
    tips_ru: ['Высокоскоростной поезд удобная альтернатива', 'Air China и China Eastern основные'],
    tips_en: ['High-speed train is convenient alternative', 'Air China and China Eastern are main'] },
  { from: 'HKG', to: 'SIN', fromCity_ru: 'Гонконг', toCity_ru: 'Сингапур', fromCity_en: 'Hong Kong', toCity_en: 'Singapore',
    tips_ru: ['4 часа полёта на юг', 'Cathay Pacific — премиум вариант'],
    tips_en: ['4 hour flight south', 'Cathay Pacific is premium option'] },
  { from: 'SIN', to: 'HKG', fromCity_ru: 'Сингапур', toCity_ru: 'Гонконг', fromCity_en: 'Singapore', toCity_en: 'Hong Kong',
    tips_ru: ['Singapore Airlines отличный сервис', 'Scoot дешёвая альтернатива'],
    tips_en: ['Singapore Airlines excellent service', 'Scoot is cheap alternative'] },
  { from: 'DEL', to: 'BOM', fromCity_ru: 'Дели', toCity_ru: 'Мумбаи', fromCity_en: 'Delhi', toCity_en: 'Mumbai',
    tips_ru: ['2 часа полёта — самый загруженный маршрут Индии', 'IndiGo — лоукостер лидер'],
    tips_en: ['2 hour flight — India\'s busiest route', 'IndiGo is budget leader'] },
  { from: 'BOM', to: 'DEL', fromCity_ru: 'Мумбаи', toCity_ru: 'Дели', fromCity_en: 'Mumbai', toCity_en: 'Delhi',
    tips_ru: ['Air India и Vistara также летают', 'Бронируй заранее — быстро раскупается'],
    tips_en: ['Air India and Vistara also fly', 'Book early — sells out fast'] },
  { from: 'CGK', to: 'SIN', fromCity_ru: 'Джакарта', toCity_ru: 'Сингапур', fromCity_en: 'Jakarta', toCity_en: 'Singapore',
    tips_ru: ['2 часа полёта на север', 'Lion Air и AirAsia супердёшево'],
    tips_en: ['2 hour flight north', 'Lion Air and AirAsia super cheap'] },
  { from: 'SIN', to: 'CGK', fromCity_ru: 'Сингапур', toCity_ru: 'Джакарта', fromCity_en: 'Singapore', toCity_en: 'Jakarta',
    tips_ru: ['Soekarno-Hatta огромный аэропорт', 'Garuda Indonesia — премиум вариант'],
    tips_en: ['Soekarno-Hatta is huge airport', 'Garuda Indonesia is premium option'] },
  { from: 'BKK', to: 'HAN', fromCity_ru: 'Бангкок', toCity_ru: 'Ханой', fromCity_en: 'Bangkok', toCity_en: 'Hanoi',
    tips_ru: ['1.5 часа полёта на восток', 'VietJet Air — вьетнамский лоукостер'],
    tips_en: ['1.5 hour flight east', 'VietJet Air is Vietnamese budget carrier'] },
  { from: 'HAN', to: 'BKK', fromCity_ru: 'Ханой', toCity_ru: 'Бангкок', fromCity_en: 'Hanoi', toCity_en: 'Bangkok',
    tips_ru: ['Vietnam Airlines флагман', 'Noi Bai аэропорт далеко от центра'],
    tips_en: ['Vietnam Airlines is flagship', 'Noi Bai airport far from center'] },

  // ===== MIDDLE EAST (15 routes) =====
  { from: 'DXB', to: 'IST', fromCity_ru: 'Дубай', toCity_ru: 'Стамбул', fromCity_en: 'Dubai', toCity_en: 'Istanbul',
    tips_ru: ['5 часов полёта на запад', 'Emirates и Turkish Airlines летают часто', 'Удобный хаб для пересадок'],
    tips_en: ['5 hour flight west', 'Emirates and Turkish Airlines fly frequently', 'Convenient hub for connections'] },
  { from: 'IST', to: 'DXB', fromCity_ru: 'Стамбул', toCity_ru: 'Дубай', fromCity_en: 'Istanbul', toCity_en: 'Dubai',
    tips_ru: ['FlyDubai дешевле Emirates', 'Pegasus через Sabiha Gokcen'],
    tips_en: ['FlyDubai cheaper than Emirates', 'Pegasus via Sabiha Gokcen'] },
  { from: 'DOH', to: 'CAI', fromCity_ru: 'Доха', toCity_ru: 'Каир', fromCity_en: 'Doha', toCity_en: 'Cairo',
    tips_ru: ['3 часа полёта на запад', 'Qatar Airways — премиум перевозчик'],
    tips_en: ['3 hour flight west', 'Qatar Airways is premium carrier'] },
  { from: 'CAI', to: 'DOH', fromCity_ru: 'Каир', toCity_ru: 'Доха', fromCity_en: 'Cairo', toCity_en: 'Doha',
    tips_ru: ['EgyptAir национальный перевозчик', 'Hamad Airport новый и роскошный'],
    tips_en: ['EgyptAir is national carrier', 'Hamad Airport new and luxurious'] },
  { from: 'DXB', to: 'CAI', fromCity_ru: 'Дубай', toCity_ru: 'Каир', fromCity_en: 'Dubai', toCity_en: 'Cairo',
    tips_ru: ['4 часа полёта через Красное море', 'FlyDubai и EgyptAir летают'],
    tips_en: ['4 hour flight across Red Sea', 'FlyDubai and EgyptAir fly'] },
  { from: 'CAI', to: 'DXB', fromCity_ru: 'Каир', toCity_ru: 'Дубай', fromCity_en: 'Cairo', toCity_en: 'Dubai',
    tips_ru: ['Cairo Airport старый — приезжай заранее', 'Air Arabia дешёвая из Sharjah'],
    tips_en: ['Cairo Airport is old — arrive early', 'Air Arabia cheap from Sharjah'] },
  { from: 'JED', to: 'CAI', fromCity_ru: 'Джидда', toCity_ru: 'Каир', fromCity_en: 'Jeddah', toCity_en: 'Cairo',
    tips_ru: ['2 часа полёта через Красное море', 'Saudia и EgyptAir основные'],
    tips_en: ['2 hour flight across Red Sea', 'Saudia and EgyptAir are main'] },
  { from: 'CAI', to: 'JED', fromCity_ru: 'Каир', toCity_ru: 'Джидда', fromCity_en: 'Cairo', toCity_en: 'Jeddah',
    tips_ru: ['Много паломников — высокий спрос', 'Flynas бюджетная саудовская'],
    tips_en: ['Many pilgrims — high demand', 'Flynas is Saudi budget carrier'] },
  { from: 'DXB', to: 'BOM', fromCity_ru: 'Дубай', toCity_ru: 'Мумбаи', fromCity_en: 'Dubai', toCity_en: 'Mumbai',
    tips_ru: ['3 часа полёта на восток', 'Emirates и Air India Express летают'],
    tips_en: ['3 hour flight east', 'Emirates and Air India Express fly'] },
  { from: 'BOM', to: 'DXB', fromCity_ru: 'Мумбаи', toCity_ru: 'Дубай', fromCity_en: 'Mumbai', toCity_en: 'Dubai',
    tips_ru: ['IndiGo дешевле премиум перевозчиков', 'Много индийцев работает в ОАЭ'],
    tips_en: ['IndiGo cheaper than premium carriers', 'Many Indians work in UAE'] },
  { from: 'DXB', to: 'DEL', fromCity_ru: 'Дубай', toCity_ru: 'Дели', fromCity_en: 'Dubai', toCity_en: 'Delhi',
    tips_ru: ['3.5 часа полёта на восток', 'Emirates — премиум, Air India Express — бюджет'],
    tips_en: ['3.5 hour flight east', 'Emirates premium, Air India Express budget'] },
  { from: 'DEL', to: 'DXB', fromCity_ru: 'Дели', toCity_ru: 'Дубай', fromCity_en: 'Delhi', toCity_en: 'Dubai',
    tips_ru: ['Flydubai дешевле Emirates', 'Много рейсов каждый день'],
    tips_en: ['Flydubai cheaper than Emirates', 'Many flights daily'] },
  { from: 'RUH', to: 'DXB', fromCity_ru: 'Эр-Рияд', toCity_ru: 'Дубай', fromCity_en: 'Riyadh', toCity_en: 'Dubai',
    tips_ru: ['2 часа полёта на восток', 'Saudia и FlyDubai основные'],
    tips_en: ['2 hour flight east', 'Saudia and FlyDubai are main'] },
  { from: 'DXB', to: 'RUH', fromCity_ru: 'Дубай', toCity_ru: 'Эр-Рияд', fromCity_en: 'Dubai', toCity_en: 'Riyadh',
    tips_ru: ['Flynas — саудовский лоукостер', 'King Khalid Airport новый терминал'],
    tips_en: ['Flynas is Saudi budget carrier', 'King Khalid Airport has new terminal'] },
  { from: 'AMM', to: 'DXB', fromCity_ru: 'Амман', toCity_ru: 'Дубай', fromCity_en: 'Amman', toCity_en: 'Dubai',
    tips_ru: ['3 часа полёта на восток', 'Royal Jordanian и FlyDubai летают'],
    tips_en: ['3 hour flight east', 'Royal Jordanian and FlyDubai fly'] },
];

/** Lookup city names and tips for a route */
export function getRouteInfo(from, to, lang = 'ru') {
  const found = POPULAR_ROUTES.find(
    (r) => r.from === from && r.to === to,
  );
  if (found) {
    return {
      fromCity: lang === 'ru' ? found.fromCity_ru : found.fromCity_en,
      toCity: lang === 'ru' ? found.toCity_ru : found.toCity_en,
      tips: lang === 'ru' ? found.tips_ru : found.tips_en,
    };
  }
  // Fallback: use IATA codes
  return { fromCity: from, toCity: to, tips: [] };
}
